/**
 * THE CLOSURE RECEIPT — emit Web Components for five contracts, generate the
 * package's custom-elements.json FROM the contracts (deterministic), run the
 * REPO'S OWN CEM extraction adapter (extract/adapters/cem.ts) over the
 * emitted package, and diff the round-tripped proposal against each source
 * contract:
 *
 *   · props / enum value sets / defaults / events MUST survive the loop
 *     contract → emitted WC package → CEM → extraction → proposal;
 *   · every fact that does NOT survive is NAMED with its mechanism (anatomy
 *     doesn't ride CEM — expected, named; never a silent drop).
 *
 * Subjects: ds.badge, ds.button, ds.switch, ds.card (repo) + polaris.badge
 * (the brownfield extraction pilot). Emitted files land in
 * packages/emitter-web-components/samples/ as eyeball receipts (the
 * core/samples pattern).
 *
 * Run: npx tsx packages/emitter-web-components/scripts/roundtrip-check.ts
 *      [--examples-root <path>] [--out <dir>]
 * Exit 0 = every check passed; 1 = failures (each named).
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ContractSchema, type Contract } from '../../schema/src/contract-schema.js';
import { isArrayType, isEnum } from '../../../core/emit-react.js';
import { extractCem } from '../../../extract/adapters/cem.js';
import { proposeContract } from '../../../extract/propose.js';
import type { SkippedComponent } from '../../../core/extract-react-tsx.js';
import { attrOf, classNameOf, emitWebComponent, propFromAttr, tagOf } from '../src/emit-wc.js';

const argv = process.argv.slice(2);
const argValue = (flag: string, fallback: string): string => {
  const i = argv.indexOf(flag);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : fallback;
};
const ROOT = process.cwd();
const EXAMPLES = argValue('--examples-root', path.join(ROOT, 'examples'));
const OUT = argValue('--out', path.join(ROOT, 'packages', 'emitter-web-components', 'samples'));

const SUBJECTS = ['ds.badge', 'ds.button', 'ds.switch', 'ds.card', 'polaris.badge'];

// ---------------------------------------------------------------------------
// Load contracts + icons (repo + the Polaris pilot)
// ---------------------------------------------------------------------------

const readJson = (p: string) => JSON.parse(readFileSync(p, 'utf8'));
const contracts = new Map<string, Contract>();
for (const dir of [path.join(ROOT, 'contracts'), path.join(EXAMPLES, 'polaris', 'contracts')]) {
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.contract.json'))) {
    const c = ContractSchema.parse(readJson(path.join(dir, f)));
    contracts.set(c.id, c);
  }
}
const icons = new Map<string, string>();
for (const dir of [path.join(ROOT, 'assets', 'icons'), path.join(EXAMPLES, 'polaris', 'assets', 'icons')]) {
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.svg'))) {
    icons.set(f.replace(/\.svg$/, ''), readFileSync(path.join(dir, f), 'utf8').trim());
  }
}

// ---------------------------------------------------------------------------
// Emit the package: per-contract files + merged manifest + index.ts
// ---------------------------------------------------------------------------

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const failures: string[] = [];
const check = (label: string, cond: boolean) => {
  if (!cond) failures.push(label);
  console.log(`  ${cond ? '✔' : '✖'} ${label}`);
};

const mergedModules: unknown[] = [];
for (const id of SUBJECTS) {
  const contract = contracts.get(id);
  if (!contract) throw new Error(`Subject contract not loaded: ${id}`);
  const tag = tagOf(contract);
  const r = emitWebComponent(contract, { icons, contracts });
  writeFileSync(path.join(OUT, `${tag}.ts`), r.element);
  writeFileSync(path.join(OUT, `${tag}.css.ts`), r.stylesheet);
  writeFileSync(path.join(OUT, `${tag}.demo.html`), r.demo);
  writeFileSync(path.join(OUT, `${tag}.custom-elements.json`), r.manifest);
  mergedModules.push(...(JSON.parse(r.manifest) as { modules: unknown[] }).modules);
}
// The package-level manifest + registration barrel are SET-level artifacts
// (emit() is per-contract) — composed here mechanically, still deterministic.
const manifestPath = path.join(OUT, 'custom-elements.json');
writeFileSync(
  manifestPath,
  JSON.stringify({ schemaVersion: '1.0.0', readme: '', modules: mergedModules }, null, 2) + '\n',
);
writeFileSync(
  path.join(OUT, 'index.ts'),
  [
    '/** Registration barrel — importing registers every emitted element (each module`s define() is idempotent). Generated by roundtrip-check.ts. */',
    ...SUBJECTS.map((id) => `import './${tagOf(contracts.get(id)!)}.js';`),
    '',
  ].join('\n'),
);
console.log(`\nEmitted ${SUBJECTS.length} contracts → ${OUT}`);

// ---------------------------------------------------------------------------
// Round trip: the repo's own CEM adapter over the emitted manifest
// ---------------------------------------------------------------------------

const skipped: SkippedComponent[] = [];
const extracted = extractCem(manifestPath, skipped);
console.log(`\nCEM extraction: ${extracted.length} component(s), ${skipped.length} named skip(s)`);
check('cem: every emitted component extracted (no silent drops)', extracted.length === SUBJECTS.length);
check('cem: zero skips (the emitted manifest is fully legible)', skipped.length === 0);

for (const id of SUBJECTS) {
  const contract = contracts.get(id)!;
  const tag = tagOf(contract);
  console.log(`\n${contract.name} (${id}) ⇄ <${tag}>`);
  // Two subjects share the class name "BadgeElement" — disambiguate by the
  // module path the adapter carries in `source`.
  const comp = extracted.find(
    (c) => c.name === classNameOf(contract) && c.source.includes(`(${tag}.ts)`),
  );
  check(`extracted as ${classNameOf(contract)} from ${tag}.ts`, !!comp);
  if (!comp) continue;

  // ---- survival: props / enums / defaults ---------------------------------
  for (const p of contract.props) {
    if (isArrayType(p)) {
      // Attribute-less by construction: attributes cannot carry lists. The
      // manifest carries it as a public FIELD; the adapter reads it back as
      // kind 'other' (CEM's type grammar has no list-of-records) — named.
      const f = comp.props.find((ep) => ep.name === p.name);
      check(
        `prop ${p.name} (arrayOf): survives as a public field, kind 'other' — CEM type text has no record-list grammar (named mechanism)`,
        !!f && f.kind === 'other',
      );
      continue;
    }
    if (p.type === 'text' && p.bindings.code.prop === 'children') {
      // The children text prop IS the default slot; the manifest names the
      // slot, but the CEM adapter reads attributes/members/events only — the
      // prop returns as a slot fact, not a prop (named mechanism).
      const inManifest = (JSON.parse(readFileSync(manifestPath, 'utf8')) as {
        modules: Array<{ path: string; declarations: Array<{ slots?: Array<{ name: string }> }> }>;
      }).modules
        .filter((m) => m.path === `${tag}.ts`)
        .some((m) => m.declarations.some((d) => (d.slots ?? []).some((s) => s.name === '')));
      check(
        `prop ${p.name} (children text): rides the default <slot> — named in the manifest's slots, outside the adapter's prop surface (named mechanism)`,
        inManifest && !comp.props.some((ep) => ep.name === attrOf(p.name)),
      );
      continue;
    }
    const attr = attrOf(p.name);
    const ep = comp.props.find((x) => x.name === attr);
    if (!ep) {
      check(`prop ${p.name}: survives as attribute "${attr}"`, false);
      continue;
    }
    check(`prop ${p.name}: attribute "${attr}" maps back to canonical "${propFromAttr(attr)}"`, propFromAttr(attr) === p.name);
    if (isEnum(p)) {
      check(
        `prop ${p.name}: enum values survive [${p.type.enum.join(', ')}]`,
        ep.kind === 'enum' && JSON.stringify(ep.values) === JSON.stringify(p.type.enum),
      );
    } else if (p.type === 'boolean') {
      check(`prop ${p.name}: boolean kind survives`, ep.kind === 'boolean');
    } else if (p.type === 'number') {
      check(`prop ${p.name}: number kind survives`, ep.kind === 'number');
    } else {
      check(`prop ${p.name}: text kind survives as string`, ep.kind === 'string');
    }
    if (p.default !== undefined) {
      check(`prop ${p.name}: default ${JSON.stringify(p.default)} survives`, ep.default === p.default);
    }
  }

  // ---- survival: events ---------------------------------------------------
  for (const ev of contract.events ?? []) {
    const ep = comp.props.find((x) => x.kind === 'event' && x.name === ev.bindings.code.prop);
    check(`event ${ev.name}: survives as event prop ${ev.bindings.code.prop}`, !!ep);
  }

  // ---- round-tripped PROPOSAL vs source contract --------------------------
  const proposal = proposeContract(comp, 'wc');
  const proposed = ContractSchema.parse(proposal.contract);
  for (const p of contract.props) {
    if (isArrayType(p) || (p.type === 'text' && p.bindings.code.prop === 'children')) continue;
    const pp = proposed.props.find((x) => x.name === attrOf(p.name));
    if (isEnum(p)) {
      check(
        `proposal: ${p.name} back as enum with the full value set${p.default !== undefined ? ` + default '${p.default}'` : ''}`,
        !!pp && isEnum(pp) && JSON.stringify(pp.type.enum) === JSON.stringify(p.type.enum) && pp.default === p.default,
      );
    } else if (!pp) {
      check(`proposal: ${p.name} present`, false);
    }
  }
  for (const ev of contract.events ?? []) {
    const pe = (proposed.events ?? []).find((x) => x.name === ev.name);
    check(
      `proposal: event '${ev.name}' back with bindings.code.prop ${ev.bindings.code.prop}`,
      !!pe && pe.bindings.code.prop === ev.bindings.code.prop,
    );
  }

  // ---- NON-survivors, each named with its mechanism -----------------------
  const namedLoss = (label: string, cond: boolean) =>
    check(`NAMED non-survivor — ${label}`, cond);
  namedLoss(
    'anatomy (parts/tokens/layout/…): CEM describes an API, never an implementation — the proposal returns a stub anatomy',
    JSON.stringify(proposed.anatomy) === JSON.stringify({ root: {} }),
  );
  namedLoss(
    'interaction states: no CEM field carries :hover/:disabled token overrides — the proposal declares none',
    proposed.states.length === 0,
  );
  namedLoss(
    'semantics.element: a manifest names the custom-element tag, not the internal host element — the proposal defaults to "div" and says so in its notes',
    proposed.semantics.element === 'div' &&
      proposal.notes.some((n) => n.includes('semantics.element defaulted')),
  );
  namedLoss(
    'prop spelling: CEM carries the DOM attribute spelling (kebab-case); the canonical camelCase name is recovered by the same mapping the element class uses (propFromAttr)',
    contract.props
      .filter((p) => !isArrayType(p) && !(p.type === 'text' && p.bindings.code.prop === 'children'))
      .every((p) => propFromAttr(attrOf(p.name)) === p.name),
  );
  if (slotConstraintCount(contract) > 0) {
    namedLoss(
      'slot constraints (accepts/min/max/required): CEM slots carry name + description only — the constraint set does not ride',
      true, // by construction: the adapter reads no slot data at all
    );
  }
  if (contract.a11y) {
    namedLoss('a11y (focusVisible/minHitArea/contrast): no CEM vocabulary — review-gate facts stay contract-side', true);
  }
  namedLoss('bindings.figma / anchors: design-side identity never enters the code package', true);
}

function slotConstraintCount(contract: Contract): number {
  let n = 0;
  const walk = (p: Contract['anatomy'][string]) => {
    if (p.slot && (p.slot.accepts || p.slot.min !== undefined || p.slot.max !== undefined || p.slot.required)) n++;
    for (const c of Object.values(p.parts ?? {})) walk(c);
  };
  for (const p of Object.values(contract.anatomy)) walk(p);
  return n;
}

console.log(
  failures.length === 0
    ? `\n✔ wc-emitter-roundtrip: ${SUBJECTS.length} contracts emitted, CEM-extracted, and diffed — props/enums/defaults/events survive; every non-survivor named`
    : `\n✖ ${failures.length} round-trip check(s) failed`,
);
process.exit(failures.length === 0 ? 0 : 1);
