// GENERATED by scripts/generate-figma.ts — DO NOT EDIT.
// Source of truth: contracts/composite-modal.contract.json (ds.composite-modal v1.1.0)
// Amend-capable (#60): an existing component (set) carrying our identity
// marker is reconciled IN PLACE (same node id + key); unchanged specs skip.
const COMPONENTS = [
  {
    "setName": "CompositeModal",
    "contractId": "ds.composite-modal",
    "anchorKey": null,
    "description": "CompositeModal — generated from contract ds.composite-modal v1.1.0 †",
    "isSet": false,
    "boolProps": [],
    "textProps": [],
    "fontStyles": [
      "Medium"
    ],
    "variants": [
      {
        "name": "CompositeModal",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "CompositeModal",
          "layout": {
            "mode": "VERTICAL",
            "primary": "MIN",
            "counter": "MIN",
            "stretchChildren": true
          },
          "children": [
            {
              "type": "frame",
              "name": "backdrop",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "MIN",
                "counter": "MIN"
              },
              "insetOverlay": true,
              "lits": {
                "fillColor": {
                  "r": 0,
                  "g": 0,
                  "b": 0,
                  "a": 0.4
                }
              },
              "children": []
            },
            {
              "type": "frame",
              "name": "dialog",
              "layout": {
                "mode": "VERTICAL",
                "primary": "MIN",
                "counter": "MIN",
                "stretchChildren": true
              },
              "fill": "color/surface/raised",
              "stroke": "color/border/subtle",
              "bindings": {
                "strokeWeight": "border-width/100",
                "topLeftRadius": "radius/card",
                "topRightRadius": "radius/card",
                "bottomLeftRadius": "radius/card",
                "bottomRightRadius": "radius/card",
                "paddingLeft": "space/inset-x/lg",
                "paddingRight": "space/inset-x/lg",
                "paddingTop": "space/inset-y/lg",
                "paddingBottom": "space/inset-y/lg",
                "itemSpacing": "space/gap/md"
              },
              "lits": {
                "width": 480
              },
              "children": [
                {
                  "type": "frame",
                  "name": "header",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "SPACE_BETWEEN",
                    "counter": "CENTER"
                  },
                  "children": [
                    {
                      "type": "text",
                      "name": "title",
                      "characters": "Order details",
                      "fontSize": 14,
                      "fontStyle": "Medium"
                    },
                    {
                      "type": "svg",
                      "name": "close",
                      "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" width=\"20\" height=\"20\" fill=\"none\" stroke=\"#000000\" stroke-width=\"1.5\"><line x1=\"5\" y1=\"5\" x2=\"15\" y2=\"15\" stroke-linecap=\"round\"/><line x1=\"15\" y1=\"5\" x2=\"5\" y2=\"15\" stroke-linecap=\"round\"/></svg>",
                      "iconSize": 20
                    }
                  ],
                  "fillW": true
                },
                {
                  "type": "frame",
                  "name": "body",
                  "layout": {
                    "mode": "VERTICAL",
                    "primary": "MIN",
                    "counter": "MIN",
                    "stretchChildren": true
                  },
                  "bindings": {
                    "itemSpacing": "space/gap/sm"
                  },
                  "children": [
                    {
                      "type": "instance",
                      "name": "summary",
                      "dep": "Card",
                      "depProps": {
                        "Title": "Order summary"
                      }
                    },
                    {
                      "type": "frame",
                      "name": "tags",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "MIN",
                        "counter": "CENTER",
                        "wrap": true
                      },
                      "bindings": {
                        "itemSpacing": "space/gap/sm"
                      },
                      "children": [
                        {
                          "type": "instance",
                          "name": "tag",
                          "dep": "Badge",
                          "depProps": {
                            "Label": "Shipping"
                          }
                        },
                        {
                          "type": "instance",
                          "name": "tag 2",
                          "dep": "Badge",
                          "depProps": {
                            "Label": "Gift wrap"
                          }
                        },
                        {
                          "type": "instance",
                          "name": "tag 3",
                          "dep": "Badge",
                          "depProps": {
                            "Label": "Priority"
                          }
                        }
                      ],
                      "fillW": true
                    }
                  ],
                  "fillW": true
                },
                {
                  "type": "frame",
                  "name": "footer",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "MAX",
                    "counter": "CENTER"
                  },
                  "bindings": {
                    "itemSpacing": "space/gap/control"
                  },
                  "children": [
                    {
                      "type": "instance",
                      "name": "cancel",
                      "dep": "Button",
                      "depProps": {
                        "Label": "Cancel",
                        "Variant": "Secondary"
                      }
                    },
                    {
                      "type": "instance",
                      "name": "save",
                      "dep": "Button",
                      "depProps": {
                        "Label": "Save",
                        "Variant": "Primary"
                      }
                    }
                  ],
                  "fillW": true
                }
              ]
            }
          ]
        }
      }
    ],
    "colW": 380
  }
];
const ROW_H = 240, PAD = 40;

const EXPECTED_FILE_KEY = null;
if (EXPECTED_FILE_KEY && figma.fileKey && figma.fileKey !== EXPECTED_FILE_KEY) {
  throw new Error('WRONG FILE: expected ' + EXPECTED_FILE_KEY + ', got ' + figma.fileKey);
}

await figma.loadAllPagesAsync();

const allVars = await figma.variables.getLocalVariablesAsync();
const varByName = {};
for (const v of allVars) varByName[v.name] = v;
const need = (name) => {
  const v = varByName[name];
  if (!v) throw new Error('Missing variable: ' + name);
  return v;
};
const boundPaint = (varName, consumer) => {
  // Seed the base with the resolved value when a consumer node is known:
  // Figma keeps rendering a reassigned bound paint's BASE color on
  // pre-existing nodes (fresh nodes normalize at assignment) — without the
  // seed, amended variants render black. The binding itself is unchanged.
  // B-3 finding 2: the resolved ALPHA rides the seed too (paint opacity) —
  // discarding it rendered Badge's rgba(0,0,0,.06) pill as opaque black on
  // amended nodes.
  const v = need(varName);
  let base = { r: 0, g: 0, b: 0 };
  let alpha = 1;
  if (consumer) {
    try {
      const r = v.resolveForConsumer(consumer);
      if (r && r.value && r.value.r !== undefined) {
        base = { r: r.value.r, g: r.value.g, b: r.value.b };
        if (typeof r.value.a === 'number') alpha = r.value.a;
      }
    } catch (e) { /* fall back to black base */ }
  }
  return figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: base, opacity: alpha }, 'color', v);
};

// Named text styles (synced by 01-tokens.js): consumers look up OUR styles
// only — the ds_contracts/textStyleToken marker is identity, a foreign style
// sharing a name is never used. Missing style (tokens script not run yet)
// degrades gracefully: the raw fontName/fontSize already set on the node
// stand until the next amend after the styles exist.
let _textStyleMap = null;
async function ourTextStyle(name) {
  if (!_textStyleMap) {
    _textStyleMap = {};
    for (const s of await figma.getLocalTextStylesAsync()) {
      if (s.getSharedPluginData('ds_contracts', 'textStyleToken')) _textStyleMap[s.name] = s;
    }
  }
  return _textStyleMap[name] || null;
}

const fontStyles = new Set(['Medium']);
for (const C of COMPONENTS) for (const s of C.fontStyles) fontStyles.add(s);
for (const style of fontStyles) {
  await figma.loadFontAsync({ family: 'Inter', style });
}

// State previews (figmaStatePreviews): merge the enum-API cartesian with the
// canvas-only preview overlay; base variants gain an explicit State=Default
// segment so every variant in the set carries the axis (Figma derives
// variant properties from names). Contracts without previews pass through
// untouched — names, hashes, and amend reconciliation are unchanged.
function withStateAxis(C) {
  if (!C.stateVariants || C.stateVariants.length === 0) return C.variants;
  return C.variants.map((v) => {
    const name = v.name.indexOf('=') >= 0 ? v.name + ', State=Default' : 'State=Default';
    return Object.assign({}, v, { name: name, spec: Object.assign({}, v.spec, { name: name }) });
  }).concat(C.stateVariants);
}

function findComponentByName(name) {
  for (const page of figma.root.children) {
    const hit = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === name,
    );
    if (hit) return hit;
  }
  throw new Error('Dependency component not found in file: ' + name + ' (sync it first)');
}

function setInstanceProps(inst, props, owner) {
  // REAL-FIGMA QUIRK (live finding 2026-07-22, pinned by the named refusal +
  // Desktop Bridge probes; supersedes the 07-21 "mixed VARIANT+TEXT call"
  // inference, which was wrong): a freshly created instance's
  // componentProperties can LAG behind its component set within a session,
  // listing only the VARIANT axes — the live composite refused with
  // "available: Variant, Size, State" on a Button set that demonstrably
  // carried Label/Disabled/Loading. The set's componentPropertyDefinitions
  // are always complete, and setProperties with the FULL set-level key
  // applies correctly even while the instance's view lags (probe-verified).
  // So: resolve against the instance first, fall back to the OWNER's
  // definitions, and refuse by name only when neither knows the property.
  const instProps = inst.componentProperties;
  const instKeys = Object.keys(instProps);
  let ownerDefs = {};
  try { ownerDefs = (owner && owner.componentPropertyDefinitions) || {}; } catch (e) { ownerDefs = {}; }
  const ownerKeys = Object.keys(ownerDefs);
  const variantProps = {};
  const otherProps = {};
  const missing = [];
  for (const [wanted, value] of Object.entries(props)) {
    const match = (k) => k === wanted || k.startsWith(wanted + '#');
    const key = instKeys.find(match) || ownerKeys.find(match);
    if (!key) { missing.push(wanted); continue; }
    const def = instProps[key] || ownerDefs[key] || {};
    if (def.type === 'VARIANT') variantProps[key] = value; else otherProps[key] = value;
  }
  // 2026-07-21 (live-canvas finding, handoff 08#1): the old silent no-op is
  // exactly how the repeated Badge instances kept their default text live —
  // the contract said Label="Shipping", nothing matched, nothing was
  // reported, the build claimed success. A contract binding the runtime
  // cannot honor is a refusal, BY NAME, like every other refusal here.
  if (missing.length > 0) {
    const seen = instKeys.concat(ownerKeys.filter((k) => instKeys.indexOf(k) < 0));
    throw new Error(
      'Instance "' + inst.name + '": component propert' + (missing.length === 1 ? 'y "' : 'ies "') + missing.join('", "') +
      '" not found (instance + set expose: ' + (seen.map((k) => k.split('#')[0]).join(', ') || 'none') +
      ') — the dependency does not expose the properties this contract binds; sync the dependency component first',
    );
  }
  // Defensive two-phase apply (cheap): variant swap first, then non-variant
  // values on the settled instance — set-level property ids are stable
  // across the swap, so the resolved keys stay valid either way.
  if (Object.keys(variantProps).length > 0) inst.setProperties(variantProps);
  if (Object.keys(otherProps).length > 0) inst.setProperties(otherProps);
}

// Owner request (2026-07-21, roadmap P1): generated components land ON a
// named SECTION with a light background — not floating on the canvas. The
// section is identity-marked (ds_contracts/hostFor) so create and amend both
// re-fit the SAME section instead of stacking new ones; a component already
// hosted keeps its section.
function ensureHostSection(page, target, displayName) {
  const HOST_PAD = 60;
  const contractId = target.getSharedPluginData('ds_contracts', 'contractId');
  let section = null;
  for (const child of page.children) {
    if (child.type === 'SECTION' && child.getSharedPluginData('ds_contracts', 'hostFor') === contractId) {
      section = child;
      break;
    }
  }
  if (!section) {
    section = figma.createSection();
    page.appendChild(section);
    section.setSharedPluginData('ds_contracts', 'hostFor', contractId);
  }
  section.name = displayName;
  section.fills = [{ type: 'SOLID', color: { r: 0.969, g: 0.973, b: 0.98 } }];
  section.appendChild(target);
  target.x = HOST_PAD;
  target.y = HOST_PAD;
  section.resizeWithoutConstraints(target.width + HOST_PAD * 2, target.height + HOST_PAD * 2);
  section.x = 100;
  section.y = 100;
  return section;
}

let _slotUtil = null;
async function ensureSlotUtility() {
  if (_slotUtil) return _slotUtil;
  for (const page of figma.root.children) {
    const hit = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'Slot');
    if (hit) { _slotUtil = hit; return hit; }
  }
  // Fresh file: create it (found by the 2026-07-06 fresh-file rebuild test —
  // the lookup-only version threw in a blank file).
  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
  const util = figma.createComponent();
  util.name = 'Slot';
  util.layoutMode = 'HORIZONTAL';
  util.primaryAxisAlignItems = 'CENTER';
  util.counterAxisAlignItems = 'CENTER';
  util.paddingLeft = util.paddingRight = 12;
  util.paddingTop = util.paddingBottom = 8;
  util.cornerRadius = 4;
  util.fills = [];
  util.strokes = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.dashPattern = [4, 4];
  const t = figma.createText();
  t.fontName = { family: 'Inter', style: 'Medium' };
  t.fontSize = 12;
  t.characters = 'Slot';
  t.fills = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.appendChild(t);
  let utilPage = figma.root.children.find((p) => p.name === 'Utilities');
  if (!utilPage) { utilPage = figma.createPage(); utilPage.name = 'Utilities'; }
  utilPage.appendChild(util);
  util.x = 100; util.y = 100;
  _slotUtil = util;
  return util;
}

function applyFrameSpec(node, spec) {
  const l = spec.layout || { mode: 'HORIZONTAL', primary: 'MIN', counter: 'MIN' };
  node.layoutMode = l.mode;
  node.primaryAxisAlignItems = l.primary;
  node.counterAxisAlignItems = l.counter;
  if (l.wrap) node.layoutWrap = 'WRAP';
  node.primaryAxisSizingMode = 'AUTO';
  node.counterAxisSizingMode = 'AUTO';
  if (node.type === 'FRAME') node.fills = [];
  for (const [field, varName] of Object.entries(spec.bindings || {})) {
    node.setBoundVariable(field, need(varName));
  }
  if (spec.fill) node.fills = [boundPaint(spec.fill, node)];
  if (spec.stroke) {
    node.strokes = [boundPaint(spec.stroke, node)];
    node.strokeAlign = 'INSIDE';
  }
  if (spec.fixedWidth || spec.fixedHeight) {
    const w = spec.fixedWidth ? spec.fixedWidth.px : node.width;
    const h = spec.fixedHeight ? spec.fixedHeight.px : node.height;
    node.resize(w, h);
    const horizontalIsPrimary = l.mode === 'HORIZONTAL';
    if (spec.fixedWidth) {
      if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED';
      else node.counterAxisSizingMode = 'FIXED';
      node.setBoundVariable('width', need(spec.fixedWidth.varName));
    }
    if (spec.fixedHeight) {
      if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED';
      else node.primaryAxisSizingMode = 'FIXED';
      if (spec.fixedHeight.varName) node.setBoundVariable('height', need(spec.fixedHeight.varName));
    }
  }
  if (spec.lits) {
    // v14 literals: no variable to bind — plain values, compile-parsed.
    const li = spec.lits;
    if (li.paddingTop !== undefined) node.paddingTop = li.paddingTop;
    if (li.paddingBottom !== undefined) node.paddingBottom = li.paddingBottom;
    if (li.paddingLeft !== undefined) node.paddingLeft = li.paddingLeft;
    if (li.paddingRight !== undefined) node.paddingRight = li.paddingRight;
    if (li.itemSpacing !== undefined) node.itemSpacing = li.itemSpacing;
    if (li.radius !== undefined) node.cornerRadius = li.radius;
    if (li.strokeWeight !== undefined) node.strokeWeight = li.strokeWeight;
    if (li.minWidth !== undefined) { try { node.minWidth = li.minWidth; } catch (e) { /* needs auto-layout */ } }
    if (li.minHeight !== undefined) { try { node.minHeight = li.minHeight; } catch (e) { /* needs auto-layout */ } }
    // #60 fix 1 (fillClear precedence): a spec-carried fill is NEVER
    // trampled — fillClear only clears when no fill was spec'd. The compile
    // side already drops fillClear when a fill binding exists (applyLiterals);
    // this runtime guard makes the emitted script safe even for hand-fed
    // specs carrying both.
    if (li.fillClear && !spec.fill) node.fills = [];
    else if (li.fillColor) node.fills = [{ type: 'SOLID', color: { r: li.fillColor.r, g: li.fillColor.g, b: li.fillColor.b }, opacity: li.fillColor.a === undefined ? 1 : li.fillColor.a }];
    if (li.radiusCorners) {
      const rc = li.radiusCorners;
      if (rc.tl !== undefined) node.topLeftRadius = rc.tl;
      if (rc.tr !== undefined) node.topRightRadius = rc.tr;
      if (rc.bl !== undefined) node.bottomLeftRadius = rc.bl;
      if (rc.br !== undefined) node.bottomRightRadius = rc.br;
    }
    if (li.strokeSides) {
      const sw = li.strokeSides;
      if (sw.top !== undefined) node.strokeTopWeight = sw.top;
      if (sw.right !== undefined) node.strokeRightWeight = sw.right;
      if (sw.bottom !== undefined) node.strokeBottomWeight = sw.bottom;
      if (sw.left !== undefined) node.strokeLeftWeight = sw.left;
    }
    if (li.width !== undefined || li.height !== undefined) {
      node.resize(li.width !== undefined ? li.width : node.width, li.height !== undefined ? li.height : node.height);
      const horizontalIsPrimary = (spec.layout || { mode: 'HORIZONTAL' }).mode === 'HORIZONTAL';
      if (li.width !== undefined) {
        if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED'; else node.counterAxisSizingMode = 'FIXED';
      }
      if (li.height !== undefined) {
        if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED'; else node.primaryAxisSizingMode = 'FIXED';
      }
    }
  }
}

// v7 overlay: out-of-flow edge attachment. Must run AFTER appendChild —
// layoutPositioning ABSOLUTE requires an auto-layout parent.
function applyOverlay(parent, childNode, childSpec) {
  if (!childSpec.overlay) return;
  try {
    childNode.layoutPositioning = 'ABSOLUTE';
    const p = childSpec.overlay.placement;
    childNode.constraints =
      p === 'bottom' ? { horizontal: 'MIN', vertical: 'MAX' } :
      p === 'end' ? { horizontal: 'MAX', vertical: 'MIN' } :
      { horizontal: 'MIN', vertical: 'MIN' };
    if (p === 'top') { childNode.x = 0; childNode.y = -childNode.height; }
    else if (p === 'bottom') { childNode.x = 0; childNode.y = parent.height; }
    else if (p === 'start') { childNode.x = -childNode.width; childNode.y = 0; }
    else { childNode.x = parent.width; childNode.y = 0; }
  } catch (e) { /* parent not auto-layout — leave in flow */ }
}

// B-3 finding 5: an inset-0 overlay part (top/right/bottom/left all 0) is
// lowered out of flow — ABSOLUTE, stretched to the parent, BEHIND the
// in-flow siblings — matching the declared anatomy and the HTML render.
function applyInsetOverlay(parent, childNode, childSpec) {
  if (!childSpec.insetOverlay) return;
  try {
    // Round 5f (B5E finding 3): only a childless BACKDROP overlay (an
    // inset:0 fill layer — TextField's backdrop) lowers BEHIND the in-flow
    // siblings (index 0). A CONTENT overlay that carries glyphs (the Checkbox
    // check, the RadioButton dot, a remove button) must stay ON TOP at its
    // natural post-backdrop index — else the opaque backdrop sibling paints
    // over the glyph (the checkbox backdrop-over-glyph z-order the owner saw,
    // previously hand-corrected on canvas each re-amend).
    if (!childNode.children || childNode.children.length === 0) {
      parent.insertChild(0, childNode);
    }
    childNode.layoutPositioning = 'ABSOLUTE';
    childNode.constraints = { horizontal: 'STRETCH', vertical: 'STRETCH' };
    const o = childSpec.insetOffsets || { top: 0, right: 0, bottom: 0, left: 0 };
    childNode.x = o.left;
    childNode.y = o.top;
    childNode.resize(
      Math.max(1, parent.width - o.left - o.right),
      Math.max(1, parent.height - o.top - o.bottom),
    );
  } catch (e) { /* parent not auto-layout — leave in flow */ }
}

async function buildNode(spec, registry) {
  let node;
  if (spec.type === 'svg') {
    node = figma.createNodeFromSvg(spec.svg);
    node.fills = [];
    node.clipsContent = false;
    if (spec.iconSize) node.resize(spec.iconSize, spec.iconSize);
  } else if (spec.type === 'text') {
    node = figma.createText();
    node.fontName = { family: 'Inter', style: spec.fontStyle || 'Medium' };
    node.fontSize = spec.fontSize || 16;
    node.characters = spec.characters || '';
    if (spec.textStyle) {
      // Exact-definition match compiled in: ride the named style. Text
      // styles own typography only — the bound fill paint below coexists.
      const st = await ourTextStyle(spec.textStyle);
      if (st) { try { await node.setTextStyleIdAsync(st.id); } catch (e) { /* raw props stand */ } }
    }
    if (spec.textFill) node.fills = [boundPaint(spec.textFill, node)];
    if (spec.contentProp) {
      registry.texts.push({ prop: spec.contentProp, node, default: spec.characters || '' });
    }
    if (spec.fill || spec.fixedWidth || spec.fixedHeight || spec.bindings) {
      // Styled static text (page chips, dots, thumbs): wrap in a frame so
      // fills/dimensions/radius apply to a container, not the glyphs.
      const wrap = figma.createFrame();
      wrap.layoutMode = 'HORIZONTAL';
      wrap.primaryAxisAlignItems = 'CENTER';
      wrap.counterAxisAlignItems = 'CENTER';
      wrap.primaryAxisSizingMode = 'AUTO';
      wrap.counterAxisSizingMode = 'AUTO';
      wrap.fills = [];
      for (const [field, varName] of Object.entries(spec.bindings || {})) {
        wrap.setBoundVariable(field, need(varName));
      }
      if (spec.fill) wrap.fills = [boundPaint(spec.fill, wrap)];
      if (spec.stroke) { wrap.strokes = [boundPaint(spec.stroke, wrap)]; wrap.strokeAlign = 'INSIDE'; }
      if (spec.characters) wrap.appendChild(node); else node.remove();
      if (spec.fixedWidth || spec.fixedHeight) {
        wrap.resize(spec.fixedWidth ? spec.fixedWidth.px : wrap.width, spec.fixedHeight ? spec.fixedHeight.px : wrap.height);
        if (spec.fixedWidth) { wrap.primaryAxisSizingMode = 'FIXED'; wrap.setBoundVariable('width', need(spec.fixedWidth.varName)); }
        if (spec.fixedHeight) { wrap.counterAxisSizingMode = 'FIXED'; if (spec.fixedHeight.varName) wrap.setBoundVariable('height', need(spec.fixedHeight.varName)); else wrap.resize(wrap.width, spec.fixedHeight.px); }
      }
      wrap.name = spec.name;
      node = wrap;
    }
  } else if (spec.type === 'instance') {
    const target = findComponentByName(spec.dep);
    const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
    node = main.createInstance();
    if (spec.depProps) setInstanceProps(node, spec.depProps, target);
  } else if (spec.type === 'slot') {
    node = figma.createFrame();
    applyFrameSpec(node, spec);
    const defaults = spec.slotDefault || [];
    if (defaults.length === 0) {
      const util = await ensureSlotUtility();
      const inst = util.createInstance();
      node.appendChild(inst);
      registry.slots.push({ spec, wrapper: node, instance: inst, defaultId: null });
    } else {
      const instances = [];
      for (const item of defaults) {
        const target = findComponentByName(item.dep);
        const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
        const inst = main.createInstance();
        if (item.props) setInstanceProps(inst, item.props, target);
        node.appendChild(inst);
        if (spec.layout && spec.layout.stretchChildren) {
          try { inst.layoutSizingHorizontal = 'FILL'; } catch (e) { /* fixed-size deps */ }
        }
        instances.push({ inst, main });
      }
      if (defaults.length === 1) {
        registry.slots.push({ spec, wrapper: node, instance: instances[0].inst, defaultId: instances[0].main.id });
      }
    }
  } else {
    node = spec.type === 'root' ? figma.createComponent() : figma.createFrame();
    applyFrameSpec(node, spec);
  }
  node.name = spec.name;
  if (spec.visibleProp) {
    registry.visibles.push({ node, prop: spec.visibleProp, default: spec.visibleDefault === true });
  }
  for (const child of spec.children || []) {
    const childNode = await buildNode(child, registry);
    node.appendChild(childNode);
    applyOverlay(node, childNode, child);
    if (child.pct != null) {
      try {
        childNode.resize(Math.max(1, Math.round(node.width * child.pct)), childNode.height);
        childNode.primaryAxisSizingMode = 'FIXED';
      } catch (e) { /* track not fixed-width */ }
    }
    if (
      child.type === 'frame' && (!child.children || child.children.length === 0) &&
      !child.fixedHeight && !(child.lits && child.lits.height !== undefined) && !child.shape
    ) {
      // #60 fix 4: empty runtime-sized geometry gets DECLARED defaults —
      // height follows the auto-layout parent (FILL), never Figma's 100×100
      // createFrame artifact (Phase B-2 finding 4: ProgressBar indicators
      // overflowed their fixed-height tracks). Width stays the spec'd
      // fraction (meter pct) or the placeholder box, named in the component
      // description.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    // FILL is compiled (annotateFillW): candidates only fill when the parent
    // width is established — the hug↔fill collapse class stays impossible.
    if (child.fillW && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    }
    applyInsetOverlay(node, childNode, child);
  }
  return node;
}


// djb2 over the compiled spec — stored on the set so unchanged components
// skip cheaply and CHANGED ones amend in place.
function specHash(C) {
  let h = 5381; const s = JSON.stringify(C);
  for (let i = 0; i < s.length; i++) h = (((h << 5) + h) + s.charCodeAt(i)) >>> 0;
  return String(h);
}

// IN-PLACE AMEND (2026-07-08, closes the create-only gap): reconcile an
// existing COMPONENT_SET against the compiled spec while preserving what
// instances bind to — the set node + key, each variant COMPONENT node, and
// existing componentProperty IDs. Variant interiors are contract-owned and
// rebuilt from spec (manual interior edits are drift by definition);
// instance-level property overrides survive because property IDs do.
// Destructive changes (extra variants from removed enum values) are
// REPORTED, never deleted — a human retires those.
async function amendSet(set, C) {
  set.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (set.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: set.id, key: set.key };
  }
  const report = { name: C.setName, amended: true, nodeId: set.id, key: set.key,
    addedVariants: [], rebuiltVariants: 0, extraVariants: [], addedProps: [], editedDefaults: [] };
  const defs = set.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;

  for (const w of [
    ...C.boolProps.map((bp) => ({ name: bp.property, type: 'BOOLEAN', def: bp.default })),
    ...(C.textProps || []).map((tp) => ({ name: tp.property, type: 'TEXT', def: tp.default })),
  ]) {
    const k = defKey(w.name);
    if (!k) { newKeys[w.name] = set.addComponentProperty(w.name, w.type, w.def); report.addedProps.push(w.name); }
    else if (defs[k].type === w.type && defs[k].defaultValue !== w.def) {
      set.editComponentProperty(k, { defaultValue: w.def });
      report.editedDefaults.push(w.name);
    }
  }

  // Sets gaining/losing the State preview axis reconcile by RENAME, not
  // duplication: an existing variant whose name matches an expected name
  // minus the ', State=Default' segment IS that variant (instances point at
  // it), so it is renamed in place — every variant node ID is preserved.
  // Main-file finding, 2026-07-08: name-only matching built 12 duplicates
  // and stranded the 12 originals as off-axis extras.
  const EV = withStateAxis(C);
  const expected = new Map(EV.map((v) => [v.name, v]));
  for (const ch of set.children) {
    if (expected.has(ch.name)) continue;
    const gained = ch.name + ', State=Default';
    const lost = ch.name.replace(', State=Default', '');
    if (expected.has(gained) && !set.children.some((o) => o.name === gained)) {
      ch.name = gained;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(gained);
    } else if (lost !== ch.name && expected.has(lost) && !set.children.some((o) => o.name === lost)) {
      ch.name = lost;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(lost);
    } else {
      report.extraVariants.push(ch.name);
    }
  }
  const existingByName = new Map(set.children.map((ch) => [ch.name, ch]));

  for (const v of EV) {
    let comp = existingByName.get(v.name);
    const registry = { texts: [], slots: [], visibles: [] };
    if (!comp) {
      comp = await buildNode(v.spec, registry);
      set.appendChild(comp);
      report.addedVariants.push(v.name);
    } else {
      for (const child of [...comp.children]) child.remove();
      applyFrameSpec(comp, v.spec);
      for (const childSpec of v.spec.children || []) {
        const childNode = await buildNode(childSpec, registry);
        comp.appendChild(childNode);
        applyOverlay(comp, childNode, childSpec);
        if (childSpec.pct != null) {
          try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
        }
        if (
          childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
          !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
        ) {
          // #60 fix 4 (amend path): same empty-child declared default.
          try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
        }
        if (childSpec.fillW && 'layoutSizingHorizontal' in childNode) {
          try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        }
    applyInsetOverlay(comp, childNode, childSpec);
      }
      report.rebuiltVariants++;
    }
    for (const t of registry.texts) {
      let k = defKey(t.prop);
      if (!k) { k = set.addComponentProperty(t.prop, 'TEXT', t.default); newKeys[t.prop] = k; report.addedProps.push(t.prop); }
      else if (defs[k] && defs[k].defaultValue !== t.default && !report.editedDefaults.includes(t.prop)) {
        set.editComponentProperty(k, { defaultValue: t.default });
        report.editedDefaults.push(t.prop);
      }
      t.node.componentPropertyReferences = { characters: k };
    }
    for (const sl of registry.slots) {
      const util = await ensureSlotUtility();
      let k = defKey(sl.spec.slotProperty);
      if (!k) {
        const preferred = [];
        for (const depName of sl.spec.slotAccepts || []) {
          const target = findComponentByName(depName);
          preferred.push({ type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT', key: target.key });
        }
        k = set.addComponentProperty(sl.spec.slotProperty, 'INSTANCE_SWAP', sl.defaultId || util.id,
          preferred.length > 0 ? { preferredValues: preferred } : undefined);
        newKeys[sl.spec.slotProperty] = k;
        report.addedProps.push(sl.spec.slotProperty);
      }
      sl.instance.componentPropertyReferences = { mainComponent: k };
      if (sl.spec.slotOptional) {
        let vk = defKey('Show ' + sl.spec.slotProperty);
        if (!vk) { vk = set.addComponentProperty('Show ' + sl.spec.slotProperty, 'BOOLEAN', true); newKeys['Show ' + sl.spec.slotProperty] = vk; }
        sl.wrapper.componentPropertyReferences = { visible: vk };
      }
    }
    for (const vis of registry.visibles) {
      const k = defKey(vis.prop);
      if (!k) continue;
      vis.node.componentPropertyReferences = { visible: k };
      vis.node.visible = vis.default;
    }
  }

  // Contract default combo must be the FIRST variant (Figma default = first).
  const first = set.children.find((ch) => ch.name === EV[0].name);
  if (first && set.children[0] !== first) set.insertChild(0, first);

  // Grid re-layout with the create path's math.
  const specByName = new Map(EV.map((sv) => [sv.name, sv]));
  const rowsN = Math.max(...EV.map((vv) => vv.row)) + 1;
  const colsN = Math.max(...EV.map((vv) => vv.col)) + 1;
  const colWs = new Array(colsN).fill(0);
  const rowHs = new Array(rowsN).fill(0);
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    colWs[sp.col] = Math.max(colWs[sp.col], child.width);
    rowHs[sp.row] = Math.max(rowHs[sp.row], child.height);
  }
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    let x = PAD, y = PAD;
    for (let i = 0; i < sp.col; i++) x += colWs[i] + PAD;
    for (let i = 0; i < sp.row; i++) y += rowHs[i] + PAD;
    child.x = x; child.y = y;
  }
  // B-3 finding 4: after re-gridding, the SET CONTAINER refits to the
  // children's extent + grid padding (the create path's exact math) —
  // without this, added variants/columns stayed clipped by stale bounds
  // (Banner's Focus column, Button's 220-cell grid, ProgressBar's height).
  // Extra (human-owned) variants may sit beyond the grid; never shrink
  // below their extent.
  {
    let totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    let totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    for (const child of set.children) {
      totalW = Math.max(totalW, child.x + child.width + PAD);
      totalH = Math.max(totalH, child.y + child.height + PAD);
    }
    set.resizeWithoutConstraints(totalW, totalH);
  }
  set.description = C.description;
  set.setSharedPluginData('ds_contracts', 'specHash', hash);
  // Re-fit (or adopt into) the host section — legacy un-hosted sets gain one.
  const setPage = set.parent && set.parent.type === 'SECTION' ? set.parent.parent : set.parent;
  if (setPage && setPage.type === 'PAGE') ensureHostSection(setPage, set, set.name);
  return report;
}

// #60 fix 3: IN-PLACE AMEND for standalone COMPONENTs (non-set: Badge/Tag
// class) — the same identity-marker update semantics as amendSet: the
// component node (and key) instances bind to is preserved; the interior is
// contract-owned and rebuilt from spec; existing componentProperty IDs
// survive via defKey. Unchanged specs skip on the stored specHash.
async function amendComponent(comp, C) {
  comp.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (comp.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: comp.id, key: comp.key };
  }
  const report = { name: C.setName, amended: true, standalone: true, nodeId: comp.id, key: comp.key, addedProps: [], editedDefaults: [] };
  const defs = comp.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;
  for (const w of [
    ...C.boolProps.map((bp) => ({ name: bp.property, type: 'BOOLEAN', def: bp.default })),
    ...(C.textProps || []).map((tp) => ({ name: tp.property, type: 'TEXT', def: tp.default })),
  ]) {
    const k = defKey(w.name);
    if (!k) { newKeys[w.name] = comp.addComponentProperty(w.name, w.type, w.def); report.addedProps.push(w.name); }
    else if (defs[k].type === w.type && defs[k].defaultValue !== w.def) {
      comp.editComponentProperty(k, { defaultValue: w.def });
      report.editedDefaults.push(w.name);
    }
  }
  const v = C.variants[0];
  const registry = { texts: [], slots: [], visibles: [] };
  for (const child of [...comp.children]) child.remove();
  applyFrameSpec(comp, v.spec);
  for (const childSpec of v.spec.children || []) {
    const childNode = await buildNode(childSpec, registry);
    comp.appendChild(childNode);
    applyOverlay(comp, childNode, childSpec);
    if (childSpec.pct != null) {
      try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
    }
    if (
      childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
      !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
    ) {
      // #60 fix 4 (standalone amend path): same empty-child declared default.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    if (childSpec.fillW && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    }
    applyInsetOverlay(comp, childNode, childSpec);
  }
  for (const t of registry.texts) {
    let k = defKey(t.prop);
    if (!k) { k = comp.addComponentProperty(t.prop, 'TEXT', t.default); newKeys[t.prop] = k; report.addedProps.push(t.prop); }
    else if (defs[k] && defs[k].defaultValue !== t.default && !report.editedDefaults.includes(t.prop)) {
      comp.editComponentProperty(k, { defaultValue: t.default });
      report.editedDefaults.push(t.prop);
    }
    t.node.componentPropertyReferences = { characters: k };
  }
  for (const sl of registry.slots) {
    const util = await ensureSlotUtility();
    let k = defKey(sl.spec.slotProperty);
    if (!k) {
      const preferred = [];
      for (const depName of sl.spec.slotAccepts || []) {
        const target = findComponentByName(depName);
        preferred.push({ type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT', key: target.key });
      }
      k = comp.addComponentProperty(sl.spec.slotProperty, 'INSTANCE_SWAP', sl.defaultId || util.id,
        preferred.length > 0 ? { preferredValues: preferred } : undefined);
      newKeys[sl.spec.slotProperty] = k;
      report.addedProps.push(sl.spec.slotProperty);
    }
    sl.instance.componentPropertyReferences = { mainComponent: k };
    if (sl.spec.slotOptional) {
      let vk = defKey('Show ' + sl.spec.slotProperty);
      if (!vk) { vk = comp.addComponentProperty('Show ' + sl.spec.slotProperty, 'BOOLEAN', true); newKeys['Show ' + sl.spec.slotProperty] = vk; }
      sl.wrapper.componentPropertyReferences = { visible: vk };
    }
  }
  for (const vis of registry.visibles) {
    const k = defKey(vis.prop);
    if (!k) continue;
    vis.node.componentPropertyReferences = { visible: k };
    vis.node.visible = vis.default;
  }
  comp.description = C.description;
  comp.setSharedPluginData('ds_contracts', 'specHash', hash);
  // Re-fit (or adopt into) the host section — mirrors amendSet.
  const compPage2 = comp.parent && comp.parent.type === 'SECTION' ? comp.parent.parent : comp.parent;
  if (compPage2 && compPage2.type === 'PAGE') ensureHostSection(compPage2, comp, comp.name);
  return report;
}

async function syncOne(C) {
  // Identity is the ds_contracts/contractId marker, NOT the set name — in a
  // brownfield file a name can belong to the host system's own component
  // (CBDS pilot: native 72-variant "Badge"). Legacy fallback: sets created
  // before the marker existed carry only specHash under the same namespace.
  let existing = null;
  for (const page of figma.root.children) {
    existing = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') &&
        n.getSharedPluginData('ds_contracts', 'contractId') === C.contractId,
    );
    if (existing) break;
  }
  if (!existing) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName &&
          n.getSharedPluginData('ds_contracts', 'specHash') !== '',
      );
      if (existing) break;
    }
  }
  // An anchored key is ours by definition — the contract records the key the
  // canvas minted. Covers legacy nodes that predate both plugin-data markers
  // (main-file finding, 2026-07-08: 17 standalone components duplicated).
  if (!existing && C.anchorKey) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.key === C.anchorKey,
      );
      if (existing) break;
    }
    if (existing) existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  }
  if (existing && existing.type === 'COMPONENT_SET' && C.isSet) {
    return await amendSet(existing, C);
  }
  // #60 fix 3: standalone COMPONENTs (Badge/Tag class) amend in place too —
  // the "amend supports variant sets in v1" skip forced delete+recreate and
  // re-minted node ids/keys (Phase B-2 named finding 2).
  if (existing && existing.type === 'COMPONENT' && !C.isSet) {
    return await amendComponent(existing, C);
  }
  if (existing) {
    existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
    return { name: C.setName, skipped: true, reason: 'set/standalone shape mismatch (' + existing.type + ' vs isSet=' + C.isSet + ') — a human retires the old node', nodeId: existing.id, key: existing.key };
  }

  // A same-named unmarked set is foreign: leave it alone, disambiguate ours.
  let displayName = C.setName;
  for (const page of figma.root.children) {
    const foreign = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName,
    );
    if (foreign) { displayName = C.setName + ' (' + C.contractId + ')'; break; }
  }

  // One page per component (see figma-sync/arrange.js for the file layout).
  let compPage = figma.root.children.find((p) => p.name === displayName);
  if (!compPage) { compPage = figma.createPage(); compPage.name = displayName; }

  const EV = withStateAxis(C);
  const built = [];
  for (const v of EV) {
    const registry = { texts: [], slots: [], visibles: [] };
    const comp = await buildNode(v.spec, registry);
    built.push({ v, comp, registry });
  }

  let target;
  if (C.isSet) {
    // combineAsVariants requires the nodes to already be ON the parent page.
    for (const b of built) compPage.appendChild(b.comp);
    target = figma.combineAsVariants(built.map((b) => b.comp), compPage);
  } else {
    target = built[0].comp;
    compPage.appendChild(target);
  }

  // Component properties are minted on the PROPERTY OWNER — the SET for a
  // variant component, the component itself for a standalone — AFTER
  // combineAsVariants, one key per property name, wired into every variant.
  // (2026-07-21, live-canvas finding, handoff 08#1: the old per-variant
  // pre-combine minting produced id-suffixed keys that real set-instances
  // never surface, so an instance's TEXT property silently failed to apply —
  // repeated Badge instances kept the default "Badge" live. The amend path
  // (amendSet) always minted set-level; the create path now matches it.)
  const keys = {};
  const mintOnce = (name, type, def, opts) => {
    if (!keys[name]) keys[name] = target.addComponentProperty(name, type, def, opts);
    return keys[name];
  };
  for (const bp of C.boolProps) mintOnce(bp.property, 'BOOLEAN', bp.default);
  for (const tp of C.textProps || []) mintOnce(tp.property, 'TEXT', tp.default);
  for (const b of built) {
    for (const t of b.registry.texts) {
      t.node.componentPropertyReferences = { characters: mintOnce(t.prop, 'TEXT', t.default) };
    }
    for (const s of b.registry.slots) {
      const util = await ensureSlotUtility();
      let key = keys[s.spec.slotProperty];
      if (!key) {
        const preferred = [];
        for (const depName of s.spec.slotAccepts || []) {
          const dep = findComponentByName(depName);
          preferred.push({
            type: dep.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT',
            key: dep.key,
          });
        }
        key = mintOnce(
          s.spec.slotProperty,
          'INSTANCE_SWAP',
          s.defaultId || util.id,
          preferred.length > 0 ? { preferredValues: preferred } : undefined,
        );
      }
      s.instance.componentPropertyReferences = { mainComponent: key };
      if (s.spec.slotOptional) {
        s.wrapper.componentPropertyReferences = { visible: mintOnce('Show ' + s.spec.slotProperty, 'BOOLEAN', true) };
      }
    }
    for (const vis of b.registry.visibles) {
      const key = keys[vis.prop];
      if (!key) continue;
      vis.node.componentPropertyReferences = { visible: key };
      vis.node.visible = vis.default;
    }
  }

  if (C.isSet) {
    // Tight grid: rows = first axis, columns = second; per-track max sizing.
    const specByName = new Map(EV.map((s) => [s.name, s]));
    const rowsN = Math.max(...EV.map((v) => v.row)) + 1;
    const colsN = Math.max(...EV.map((v) => v.col)) + 1;
    const colWs = new Array(colsN).fill(0);
    const rowHs = new Array(rowsN).fill(0);
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      colWs[spec.col] = Math.max(colWs[spec.col], child.width);
      rowHs[spec.row] = Math.max(rowHs[spec.row], child.height);
    }
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      let x = PAD, y = PAD;
      for (let i = 0; i < spec.col; i++) x += colWs[i] + PAD;
      for (let i = 0; i < spec.row; i++) y += rowHs[i] + PAD;
      child.x = x;
      child.y = y;
    }
    const totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    const totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    target.resizeWithoutConstraints(totalW, totalH);
  }
  target.name = displayName;
  target.description = C.description;
  target.setSharedPluginData('ds_contracts', 'specHash', specHash(C));
  target.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  ensureHostSection(compPage, target, displayName);

  return {
    name: C.setName,
    nodeId: target.id,
    key: target.key,
    variants: C.isSet ? target.children.length : 1,
    properties: Object.keys(target.componentPropertyDefinitions || {}),
  };
}

const results = [];
for (const C of COMPONENTS) {
  results.push(await syncOne(C));
}
return { createdNodeIds: results.filter((r) => !r.skipped).map((r) => r.nodeId), results };
