if (figma.fileKey !== "byMp6lt0Ij9b2QbkDGFwBh") throw new Error("WRONG-FILE:" + figma.fileKey);
if (figma.root.name !== "Scratch Project") throw new Error("WRONG-FILE-NAME:" + figma.root.name);
const NS = "ds.contracts.dialog.recipe.v1";
const runIdentity = "e482eb49-b275da16-d479cda5-dialog-v1";
const pageName = "Recipe Pivot / Dialog / e482eb49-b275da16-d479cda5-dialog-v1";
const adapterIdentity = "antd-dialog-reviewed-v1";
const recipeHash = "d479cda5dd84ed7a52f65ea671e23e51695c9ce4181be9a8b8807c11fc27ea6d";
const envelopeHash = "30905d72b7c48bac63d8cab6c603ab3dc70d695a28a658655dd08f9e9313b485";
const signed = ["115:295378","163:35981","183:70641","183:69150","85:6781","173:48924","181:64873","183:74742","183:75031","183:75302","183:75495","183:75801","183:75976","183:76022","183:76063","183:76109","183:76151","183:76193","183:76259"];
await figma.loadAllPagesAsync();
const page = figma.root.children.find((c) => c.name === pageName);
if (!page) throw new Error("DIALOG-PAGE-MISSING");
if (signed.includes(page.id)) throw new Error("DIALOG-MUST-NOT-WRITE-SIGNED-PAGE:" + page.id);
if (page.getSharedPluginData(NS, "runIdentity") !== runIdentity) throw new Error("DIALOG-PAGE-IDENTITY-MISMATCH:" + page.id);
await figma.setCurrentPageAsync(page);
if (page.children.some((n) => n.type === "SECTION" && n.getSharedPluginData(NS, "adapterIdentity") === adapterIdentity))
  throw new Error("DIALOG-SECTION-EXISTS:" + adapterIdentity);
const hex = (v) => ({ r: parseInt(v.slice(1, 3), 16) / 255, g: parseInt(v.slice(3, 5), 16) / 255, b: parseInt(v.slice(5, 7), 16) / 255, a: parseInt(v.slice(7, 9), 16) / 255 });
const paint = (v) => { const c = hex(v); return { type: "SOLID", color: { r: c.r, g: c.g, b: c.b }, opacity: c.a }; };
const allFonts = await figma.listAvailableFontsAsync();
const resolvePainted = (spec) => {
  const found = spec.fallbackChain.map((c) => allFonts.find((f) => f.fontName.family === c.family && f.fontName.style === c.style)).find(Boolean);
  if (!found) throw new Error("DIALOG-FONT-UNAVAILABLE");
  if (found.fontName.family !== spec.resolvedFamily || found.fontName.style !== spec.resolvedStyle)
    throw new Error("DIALOG-FONT-PROVENANCE-TAMPER:" + found.fontName.family + ":" + found.fontName.style);
  return found.fontName;
};
const titleSpec = {"requestedFamily":"-apple-system","requestedStyle":"Semibold","resolvedFamily":"SF Pro","resolvedStyle":"Semibold","resolution":"fallback","fallbackChain":[{"family":"-apple-system","style":"Semibold"},{"family":"SF Pro","style":"Semibold"},{"family":"Roboto","style":"Medium"},{"family":"Helvetica Neue","style":"Bold"},{"family":"Arial","style":"Bold"}],"degradation":"antd --font-family is a CSS stack; Figma cannot load it; first named host font is SF Pro Semibold"};
const bodySpec = {"requestedFamily":"-apple-system","requestedStyle":"Regular","resolvedFamily":"SF Pro","resolvedStyle":"Regular","resolution":"fallback","fallbackChain":[{"family":"-apple-system","style":"Regular"},{"family":"SF Pro","style":"Regular"},{"family":"Segoe UI","style":"Regular"},{"family":"Roboto","style":"Regular"},{"family":"Helvetica Neue","style":"Regular"},{"family":"Arial","style":"Regular"}],"degradation":"antd --font-family is a CSS stack; Figma cannot load it; first named host font is SF Pro Regular"};
const titleResolved = resolvePainted(titleSpec);
const bodyResolved = resolvePainted(bodySpec);
await figma.loadFontAsync(titleResolved);
await figma.loadFontAsync(bodyResolved);
const paintedTitle = { spec: titleSpec, painted: titleResolved };
const paintedBody = { spec: bodySpec, painted: bodyResolved };
const collection = figma.variables.createVariableCollection("Recipe Dialog / " + runIdentity + " / " + adapterIdentity);
collection.renameMode(collection.modes[0].modeId, "Default");
collection.hiddenFromPublishing = true;
const modeId = collection.modes[0].modeId;
const planned = [["FLOAT","antd.dialog.paper-paddingX",24],["FLOAT","antd.dialog.paper-paddingY",20],["FLOAT","antd.dialog.paper-radius",8],["FLOAT","antd.dialog.paper-itemSpacing",8],["FLOAT","antd.dialog.paper-minWidth",520],["COLOR","antd.dialog.paper-fill","#ffffffff"],["FLOAT","antd.dialog.titleFontSize",16],["FLOAT","antd.dialog.titleLineHeight",24],["COLOR","antd.dialog.title","#000000e0"],["FLOAT","antd.dialog.bodyFontSize",14],["FLOAT","antd.dialog.bodyLineHeight",22],["COLOR","antd.dialog.body","#000000e0"]];
const vars = new Map();
for (const [type, identity, value] of planned) {
  const name = "token/" + (type === "COLOR" ? "color" : "float") + "/id-" + Array.from(identity).map((ch) => ch.charCodeAt(0).toString(16).padStart(2, "0")).join("");
  const variable = figma.variables.createVariable(name, collection, type);
  variable.scopes = ["ALL_SCOPES"];
  variable.setValueForMode(modeId, type === "COLOR" ? hex(value) : value);
  vars.set(type + ":" + identity, variable);
}
const bindColor = (base, identity) => figma.variables.setBoundVariableForPaint(base, "color", vars.get("COLOR:" + identity));
const bindFloat = (node, field, identity) => node.setBoundVariable(field, vars.get("FLOAT:" + identity));
const prefix = "antd.dialog";
const geom = {"adapterIdentity":"antd-dialog-reviewed-v1","displayName":"Ant Design","componentLabel":"Ant Design Modal","prefix":"antd.dialog","recipeHash":"d479cda5dd84ed7a52f65ea671e23e51695c9ce4181be9a8b8807c11fc27ea6d","envelopeHash":"30905d72b7c48bac63d8cab6c603ab3dc70d695a28a658655dd08f9e9313b485","titleSize":16,"titleLine":24,"titleFill":"#000000e0","bodySize":14,"bodyLine":22,"bodyFill":"#000000e0","paper":{"paddingX":24,"paddingY":20,"radius":8,"gap":8,"minWidth":520,"fill":"#ffffffff"}};
const paintText = async (characters, role, specState, size, line, fillId, sizeId, lineId) => {
  const node = figma.createText();
  node.fontName = specState.painted;
  node.characters = characters;
  node.fontSize = size;
  node.lineHeight = { unit: "PIXELS", value: line };
  node.textAlignHorizontal = "LEFT";
  node.textAlignVertical = "CENTER";
  node.textAutoResize = "WIDTH_AND_HEIGHT";
  if (node.characters.trim().length > 0 && (node.width <= 0 || node.absoluteRenderBounds === null)) {
    for (const candidate of specState.spec.fallbackChain) {
      if (candidate.family === specState.spec.resolvedFamily && candidate.style === specState.spec.resolvedStyle) continue;
      const next = allFonts.find((e) => e.fontName.family === candidate.family && e.fontName.style === candidate.style);
      if (!next) continue;
      await figma.loadFontAsync(next.fontName);
      node.fontName = next.fontName;
      node.characters = characters;
      if (node.width > 0 && node.absoluteRenderBounds) { specState.painted = next.fontName; break; }
    }
  }
  if (node.width <= 0 || node.height <= 0) throw new Error("DIALOG-TEXT-GEOMETRY:" + role);
  node.fills = [bindColor(paint(fillId === prefix + ".title" ? geom.titleFill : geom.bodyFill), fillId)];
  bindFloat(node, "fontSize", sizeId);
  bindFloat(node, "lineHeight", lineId);
  node.name = role + " :: font-provenance=" + encodeURIComponent(JSON.stringify(specState.spec));
  return node;
};
let nextX = 0;
for (const child of page.children) if (child.type === "SECTION") nextX = Math.max(nextX, child.x + child.width + 240);
const section = figma.createSection();
section.name = "Recipe Pivot / Ant Design / " + recipeHash.slice(0, 8);
section.x = nextX; section.y = 0; page.appendChild(section);
section.setSharedPluginData(NS, "adapterIdentity", adapterIdentity);
section.setSharedPluginData(NS, "recipeHash", recipeHash);
const component = figma.createComponent();
component.clipsContent = false;
component.name = "dialog/variant/default :: " + geom.componentLabel;
component.layoutMode = "VERTICAL";
component.primaryAxisAlignItems = "MIN";
component.counterAxisAlignItems = "MIN";
component.itemSpacing = geom.paper.gap;
component.paddingTop = geom.paper.paddingY;
component.paddingRight = geom.paper.paddingX;
component.paddingBottom = geom.paper.paddingY;
component.paddingLeft = geom.paper.paddingX;
component.minWidth = geom.paper.minWidth;
component.fills = [bindColor(paint(geom.paper.fill), prefix + ".paper-fill")];
component.topLeftRadius = geom.paper.radius;
component.topRightRadius = geom.paper.radius;
component.bottomRightRadius = geom.paper.radius;
component.bottomLeftRadius = geom.paper.radius;
bindFloat(component, "itemSpacing", prefix + ".paper-itemSpacing");
bindFloat(component, "paddingTop", prefix + ".paper-paddingY");
bindFloat(component, "paddingRight", prefix + ".paper-paddingX");
bindFloat(component, "paddingBottom", prefix + ".paper-paddingY");
bindFloat(component, "paddingLeft", prefix + ".paper-paddingX");
bindFloat(component, "minWidth", prefix + ".paper-minWidth");
bindFloat(component, "topLeftRadius", prefix + ".paper-radius");
bindFloat(component, "topRightRadius", prefix + ".paper-radius");
bindFloat(component, "bottomRightRadius", prefix + ".paper-radius");
bindFloat(component, "bottomLeftRadius", prefix + ".paper-radius");
section.appendChild(component);
component.appendChild(await paintText("Dialog title", "dialog/title", paintedTitle, geom.titleSize, geom.titleLine, prefix + ".title", prefix + ".titleFontSize", prefix + ".titleLineHeight"));
component.appendChild(await paintText("Dialog body", "dialog/body", paintedBody, geom.bodySize, geom.bodyLine, prefix + ".body", prefix + ".bodyFontSize", prefix + ".bodyLineHeight"));
component.layoutSizingHorizontal = "HUG";
component.layoutSizingVertical = "HUG";
const container = figma.createFrame();
container.name = "Component Container";
container.layoutMode = "NONE";
container.fills = [];
container.x = 80; container.y = 96;
section.appendChild(container);
container.appendChild(component);
container.setSharedPluginData(NS, "runIdentity", runIdentity);
container.setSharedPluginData(NS, "adapterIdentity", adapterIdentity);
container.setSharedPluginData(NS, "recipeHash", recipeHash);
container.setSharedPluginData(NS, "ownershipKey", "dialog/container");
component.setSharedPluginData(NS, "runIdentity", runIdentity);
component.setSharedPluginData(NS, "adapterIdentity", adapterIdentity);
component.setSharedPluginData(NS, "recipeHash", recipeHash);
component.setSharedPluginData(NS, "envelopeHash", envelopeHash);
component.setSharedPluginData(NS, "ownershipKey", "dialog");
section.resizeWithoutConstraints(Math.max(container.width, geom.paper.minWidth) + 160, container.y + container.height + 80);
return { pageId: page.id, sectionId: section.id, componentId: component.id, containerId: container.id, adapterIdentity, paintedTitle: paintedTitle.painted, paintedBody: paintedBody.painted };
