// GENERATED by scripts/generate-figma.ts — DO NOT EDIT.
// Source of truth: contracts/avatar.contract.json (ds.avatar v1.0.0)
let SET_NAME = "Avatar";
const CONTRACT_ID = "ds.avatar";
const DESCRIPTION = "Represents a person or entity with initials. Non-interactive. — governed by contract ds.avatar v1.0.0";
const IS_SET = true;
const BOOL_PROPS = [];
const TEXT_PROPS = [];
const FONT_STYLES = ["Medium"];
const VARIANTS = [
  {
    "name": "Size=Small",
    "row": 0,
    "col": 0,
    "spec": {
      "type": "root",
      "name": "Size=Small",
      "layout": {
        "mode": "HORIZONTAL",
        "primary": "CENTER",
        "counter": "CENTER"
      },
      "fixedWidth": {
        "px": 24,
        "varName": "size/avatar/sm"
      },
      "fixedHeight": {
        "px": 24,
        "varName": "size/avatar/sm"
      },
      "bindings": {
        "topLeftRadius": "radius/avatar",
        "topRightRadius": "radius/avatar",
        "bottomLeftRadius": "radius/avatar",
        "bottomRightRadius": "radius/avatar"
      },
      "fill": "color/identity/background",
      "children": [
        {
          "type": "text",
          "name": "label",
          "characters": "AB",
          "fontSize": 12,
          "fontStyle": "Medium",
          "textFill": "color/identity/foreground",
          "contentProp": "Initials"
        }
      ]
    }
  },
  {
    "name": "Size=Medium",
    "row": 1,
    "col": 0,
    "spec": {
      "type": "root",
      "name": "Size=Medium",
      "layout": {
        "mode": "HORIZONTAL",
        "primary": "CENTER",
        "counter": "CENTER"
      },
      "fixedWidth": {
        "px": 32,
        "varName": "size/avatar/md"
      },
      "fixedHeight": {
        "px": 32,
        "varName": "size/avatar/md"
      },
      "bindings": {
        "topLeftRadius": "radius/avatar",
        "topRightRadius": "radius/avatar",
        "bottomLeftRadius": "radius/avatar",
        "bottomRightRadius": "radius/avatar"
      },
      "fill": "color/identity/background",
      "children": [
        {
          "type": "text",
          "name": "label",
          "characters": "AB",
          "fontSize": 14,
          "fontStyle": "Medium",
          "textFill": "color/identity/foreground",
          "contentProp": "Initials"
        }
      ]
    }
  }
];
const COL_W = 380, ROW_H = 240, PAD = 40;

// File guard: multi-file bridge routing has been observed to hit the wrong
// file — never write without verifying the target.
const EXPECTED_FILE_KEY = "8nim1d0IPnehMxA7B7SYxC";
if (EXPECTED_FILE_KEY && figma.fileKey && figma.fileKey !== EXPECTED_FILE_KEY) {
  throw new Error('WRONG FILE: expected ' + EXPECTED_FILE_KEY + ', got ' + figma.fileKey);
}

await figma.loadAllPagesAsync();

// Skip if OUR component (set) already exists on ANY page (idempotency guard).
// Identity is the ds_contracts/contractId marker — a set NAME is not identity
// in a brownfield file (CBDS pilot: a native 72-variant "Badge" name-matched).
let existing = null;
for (const page of figma.root.children) {
  existing = page.findOne(
    (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') &&
      n.getSharedPluginData('ds_contracts', 'contractId') === CONTRACT_ID,
  );
  if (existing) break;
}
if (existing) return { skipped: true, nodeId: existing.id, key: existing.key };
// A same-named set WITHOUT the marker is someone else's component: never touch
// it — create ours under a disambiguated name alongside it.
for (const page of figma.root.children) {
  const foreign = page.findOne(
    (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === SET_NAME &&
      !n.getSharedPluginData('ds_contracts', 'contractId'),
  );
  if (foreign) { SET_NAME = SET_NAME + ' (' + CONTRACT_ID + ')'; break; }
}

const allVars = await figma.variables.getLocalVariablesAsync();
const varByName = {};
for (const v of allVars) varByName[v.name] = v;
const need = (name) => {
  const v = varByName[name];
  if (!v) throw new Error('Missing variable: ' + name);
  return v;
};
const boundPaint = (varName, consumer) => {
  // Seed the base with the resolved value when a consumer node is known:
  // Figma keeps rendering a reassigned bound paint's BASE color on
  // pre-existing nodes (fresh nodes normalize at assignment) — without the
  // seed, amended variants render black. The binding itself is unchanged.
  const v = need(varName);
  let base = { r: 0, g: 0, b: 0 };
  if (consumer) {
    try {
      const r = v.resolveForConsumer(consumer);
      if (r && r.value && r.value.r !== undefined) base = { r: r.value.r, g: r.value.g, b: r.value.b };
    } catch (e) { /* fall back to black base */ }
  }
  return figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: base }, 'color', v);
};

for (const style of FONT_STYLES) {
  await figma.loadFontAsync({ family: 'Inter', style });
}

function findComponentByName(name) {
  for (const page of figma.root.children) {
    const hit = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === name,
    );
    if (hit) return hit;
  }
  throw new Error('Dependency component not found in file: ' + name + ' (run its sync script first)');
}

function setInstanceProps(inst, props) {
  const available = Object.keys(inst.componentProperties);
  const resolved = {};
  for (const [wanted, value] of Object.entries(props)) {
    const key = available.find((k) => k === wanted || k.startsWith(wanted + '#'));
    if (key) resolved[key] = value;
  }
  if (Object.keys(resolved).length > 0) inst.setProperties(resolved);
}

let _slotUtil = null;
async function ensureSlotUtility() {
  if (_slotUtil) return _slotUtil;
  for (const page of figma.root.children) {
    const hit = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'Slot');
    if (hit) { _slotUtil = hit; return hit; }
  }
  const util = figma.createComponent();
  util.name = 'Slot';
  util.layoutMode = 'HORIZONTAL';
  util.primaryAxisAlignItems = 'CENTER';
  util.counterAxisAlignItems = 'CENTER';
  util.paddingLeft = util.paddingRight = 12;
  util.paddingTop = util.paddingBottom = 8;
  util.cornerRadius = 4;
  util.fills = [];
  util.strokes = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.dashPattern = [4, 4];
  const t = figma.createText();
  t.fontName = { family: 'Inter', style: 'Medium' };
  t.fontSize = 12;
  t.characters = 'Slot';
  t.fills = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.appendChild(t);
  let utilities = figma.currentPage.findOne((n) => n.type === 'SECTION' && n.name === 'Utilities');
  if (!utilities) {
    utilities = figma.createSection();
    utilities.name = 'Utilities';
    let maxX = 0;
    for (const n of figma.currentPage.children) {
      if (n !== utilities) maxX = Math.max(maxX, n.x + n.width);
    }
    utilities.x = maxX + 100;
    utilities.y = 0;
    utilities.resizeWithoutConstraints(240, 160);
  }
  utilities.appendChild(util);
  util.x = 40; util.y = 40;
  _slotUtil = util;
  return util;
}

function applyFrameSpec(node, spec) {
  const l = spec.layout || { mode: 'HORIZONTAL', primary: 'MIN', counter: 'MIN' };
  node.layoutMode = l.mode;
  node.primaryAxisAlignItems = l.primary;
  node.counterAxisAlignItems = l.counter;
  node.primaryAxisSizingMode = 'AUTO';
  node.counterAxisSizingMode = 'AUTO';
  if (node.type === 'FRAME') node.fills = [];
  for (const [field, varName] of Object.entries(spec.bindings || {})) {
    node.setBoundVariable(field, need(varName));
  }
  if (spec.fill) node.fills = [boundPaint(spec.fill, node)];
  if (spec.stroke) {
    node.strokes = [boundPaint(spec.stroke, node)];
    node.strokeAlign = 'INSIDE';
  }
  if (spec.fixedWidth || spec.fixedHeight) {
    const w = spec.fixedWidth ? spec.fixedWidth.px : node.width;
    const h = spec.fixedHeight ? spec.fixedHeight.px : node.height;
    node.resize(w, h);
    const horizontalIsPrimary = l.mode === 'HORIZONTAL';
    if (spec.fixedWidth) {
      if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED';
      else node.counterAxisSizingMode = 'FIXED';
      node.setBoundVariable('width', need(spec.fixedWidth.varName));
    }
    if (spec.fixedHeight) {
      if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED';
      else node.primaryAxisSizingMode = 'FIXED';
      node.setBoundVariable('height', need(spec.fixedHeight.varName));
    }
  }
}

async function buildNode(spec, registry) {
  let node;
  if (spec.type === 'svg') {
    node = figma.createNodeFromSvg(spec.svg);
    node.fills = [];
    node.clipsContent = false;
  } else if (spec.type === 'text') {
    node = figma.createText();
    node.fontName = { family: 'Inter', style: spec.fontStyle || 'Medium' };
    node.fontSize = spec.fontSize || 16;
    node.characters = spec.characters || '';
    if (spec.textFill) node.fills = [boundPaint(spec.textFill, node)];
    if (spec.contentProp) {
      registry.texts.push({ prop: spec.contentProp, node, default: spec.characters || '' });
    }
    if (spec.fill || spec.fixedWidth || spec.fixedHeight || spec.bindings) {
      // Styled static text (page chips, dots, thumbs): wrap in a frame so
      // fills/dimensions/radius apply to a container, not the glyphs.
      const wrap = figma.createFrame();
      wrap.layoutMode = 'HORIZONTAL';
      wrap.primaryAxisAlignItems = 'CENTER';
      wrap.counterAxisAlignItems = 'CENTER';
      wrap.primaryAxisSizingMode = 'AUTO';
      wrap.counterAxisSizingMode = 'AUTO';
      wrap.fills = [];
      for (const [field, varName] of Object.entries(spec.bindings || {})) {
        wrap.setBoundVariable(field, need(varName));
      }
      if (spec.fill) wrap.fills = [boundPaint(spec.fill, wrap)];
      if (spec.stroke) { wrap.strokes = [boundPaint(spec.stroke, wrap)]; wrap.strokeAlign = 'INSIDE'; }
      if (spec.characters) wrap.appendChild(node); else node.remove();
      if (spec.fixedWidth || spec.fixedHeight) {
        wrap.resize(spec.fixedWidth ? spec.fixedWidth.px : wrap.width, spec.fixedHeight ? spec.fixedHeight.px : wrap.height);
        if (spec.fixedWidth) { wrap.primaryAxisSizingMode = 'FIXED'; wrap.setBoundVariable('width', need(spec.fixedWidth.varName)); }
        if (spec.fixedHeight) { wrap.counterAxisSizingMode = 'FIXED'; wrap.setBoundVariable('height', need(spec.fixedHeight.varName)); }
      }
      wrap.name = spec.name;
      node = wrap;
    }
  } else if (spec.type === 'instance') {
    const target = findComponentByName(spec.dep);
    const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
    node = main.createInstance();
    if (spec.depProps) setInstanceProps(node, spec.depProps);
  } else if (spec.type === 'slot') {
    node = figma.createFrame();
    applyFrameSpec(node, spec);
    const defaults = spec.slotDefault || [];
    if (defaults.length === 0) {
      const util = await ensureSlotUtility();
      const inst = util.createInstance();
      node.appendChild(inst);
      registry.slots.push({ spec, wrapper: node, instance: inst, defaultId: null });
    } else {
      const instances = [];
      for (const item of defaults) {
        const target = findComponentByName(item.dep);
        const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
        const inst = main.createInstance();
        if (item.props) setInstanceProps(inst, item.props);
        node.appendChild(inst);
        if (spec.layout && spec.layout.stretchChildren) {
          try { inst.layoutSizingHorizontal = 'FILL'; } catch (e) { /* fixed-size deps */ }
        }
        instances.push({ inst, main });
      }
      if (defaults.length === 1) {
        // Single default → still expressible as a swap property.
        registry.slots.push({ spec, wrapper: node, instance: instances[0].inst, defaultId: instances[0].main.id });
      }
      // >1 → multi-child slot: content rendered directly, no swap property
      // (INSTANCE_SWAP holds exactly one instance; native SLOT is the fix).
    }
  } else {
    node = spec.type === 'root' ? figma.createComponent() : figma.createFrame();
    applyFrameSpec(node, spec);
  }
  node.name = spec.name;
  if (spec.visibleProp) {
    registry.visibles.push({ node, prop: spec.visibleProp, default: spec.visibleDefault === true });
  }
  for (const child of spec.children || []) {
    const childNode = await buildNode(child, registry);
    node.appendChild(childNode);
    if (child.pct != null) {
      try {
        childNode.resize(Math.max(1, Math.round(node.width * child.pct)), childNode.height);
        childNode.primaryAxisSizingMode = 'FIXED';
      } catch (e) { /* track not fixed-width */ }
    }
    if (child.grow && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    } else if (
      spec.layout && spec.layout.stretchChildren &&
      !child.fixedWidth && child.type !== 'instance' &&
      'layoutSizingHorizontal' in childNode
    ) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    }
  }
  return node;
}

// One page per component (see figma-sync/arrange.js for the file layout).
let compPage = figma.root.children.find((p) => p.name === SET_NAME);
if (!compPage) { compPage = figma.createPage(); compPage.name = SET_NAME; }

// Build every variant, then add properties BEFORE combining.
const built = [];
for (const v of VARIANTS) {
  const registry = { texts: [], slots: [], visibles: [] };
  const comp = await buildNode(v.spec, registry);
  built.push({ v, comp, registry });
}
for (const b of built) {
  for (const t of b.registry.texts) {
    const key = b.comp.addComponentProperty(t.prop, 'TEXT', t.default);
    t.node.componentPropertyReferences = { characters: key };
  }
  for (const s of b.registry.slots) {
    const util = await ensureSlotUtility();
    const preferred = [];
    for (const depName of s.spec.slotAccepts || []) {
      const target = findComponentByName(depName);
      preferred.push({
        type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT',
        key: target.key,
      });
    }
    const key = b.comp.addComponentProperty(
      s.spec.slotProperty,
      'INSTANCE_SWAP',
      s.defaultId || util.id,
      preferred.length > 0 ? { preferredValues: preferred } : undefined,
    );
    s.instance.componentPropertyReferences = { mainComponent: key };
    if (s.spec.slotOptional) {
      const vkey = b.comp.addComponentProperty('Show ' + s.spec.slotProperty, 'BOOLEAN', true);
      s.wrapper.componentPropertyReferences = { visible: vkey };
    }
  }
  const boolKeys = {};
  for (const bp of BOOL_PROPS) {
    boolKeys[bp.property] = b.comp.addComponentProperty(bp.property, 'BOOLEAN', bp.default);
  }
  for (const tp of TEXT_PROPS) {
    b.comp.addComponentProperty(tp.property, 'TEXT', tp.default);
  }
  // visibleWhen parts: visibility follows the BOOLEAN property, and the
  // canvas default matches the contract default.
  for (const vis of b.registry.visibles) {
    const key = boolKeys[vis.prop];
    if (!key) continue;
    vis.node.componentPropertyReferences = { visible: key };
    vis.node.visible = vis.default;
  }
}

let target;
if (IS_SET) {
  // combineAsVariants requires the nodes to already be ON the parent page.
  for (const b of built) compPage.appendChild(b.comp);
  target = figma.combineAsVariants(built.map((b) => b.comp), compPage);
  // Tight grid: rows = first axis, columns = second; per-track max sizing.
  const specByName = new Map(VARIANTS.map((s) => [s.name, s]));
  const rowsN = Math.max(...VARIANTS.map((v) => v.row)) + 1;
  const colsN = Math.max(...VARIANTS.map((v) => v.col)) + 1;
  const colWs = new Array(colsN).fill(0);
  const rowHs = new Array(rowsN).fill(0);
  for (const child of target.children) {
    const spec = specByName.get(child.name);
    if (!spec) continue;
    colWs[spec.col] = Math.max(colWs[spec.col], child.width);
    rowHs[spec.row] = Math.max(rowHs[spec.row], child.height);
  }
  for (const child of target.children) {
    const spec = specByName.get(child.name);
    if (!spec) continue;
    let x = PAD, y = PAD;
    for (let i = 0; i < spec.col; i++) x += colWs[i] + PAD;
    for (let i = 0; i < spec.row; i++) y += rowHs[i] + PAD;
    child.x = x;
    child.y = y;
  }
  const totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
  const totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
  target.resizeWithoutConstraints(totalW, totalH);
} else {
  target = built[0].comp;
  compPage.appendChild(target);
}
target.name = SET_NAME;
target.setSharedPluginData('ds_contracts', 'contractId', CONTRACT_ID);
target.description = DESCRIPTION;
target.x = 100;
target.y = 100;

const propNames = Object.keys(target.componentPropertyDefinitions || {});
return {
  createdNodeIds: [target.id],
  nodeId: target.id,
  key: target.key,
  variants: IS_SET ? target.children.length : 1,
  properties: propNames,
};
