/**
 * Showcase screen — generated by a catalog-constrained agent during the
 * adherence eval (evals/adherence/arm-a/account-overview.tsx), then updated
 * to use TableHeaderCell after the agent's own GAP report was promoted into
 * ds.table-row v1.1.0 (cells slot widened to accept header cells).
 *
 * Judged 100/100 adherent: every element from the catalog, one primary
 * action, layout via primitives, zero literals.
 */
import {
  Avatar,
  Badge,
  Button,
  Card,
  Inline,
  Stack,
  Table,
  TableCell,
  TableHeaderCell,
  TableRow,
} from '../components';

export function AccountOverview() {
  return (
    <Stack gap="lg">
      <Inline gap="md">
        <Avatar size="md">AC</Avatar>
        Acme Corporation
        <Badge variant="success">Active</Badge>
      </Inline>

      <Inline gap="md">
        <Card title="Plan" actions={<Button variant="secondary">Change plan</Button>}>
          Enterprise plan billed annually. Renews on Jan 1, 2027.
        </Card>
        <Card title="Seats" actions={<Button variant="secondary">Manage seats</Button>}>
          42 of 50 seats in use across your organization.
        </Card>
        <Card title="Billing" actions={<Button variant="secondary">View invoices</Button>}>
          Visa ending 4242. Next charge of $4,800 on Jan 1, 2027.
        </Card>
      </Inline>

      <Table density="comfortable">
        <TableRow>
          <TableHeaderCell>Name</TableHeaderCell>
          <TableHeaderCell>Email</TableHeaderCell>
          <TableHeaderCell>Role</TableHeaderCell>
        </TableRow>
        <TableRow>
          <TableCell>Jordan Reyes</TableCell>
          <TableCell>jordan@acme.com</TableCell>
          <TableCell>Owner</TableCell>
        </TableRow>
        <TableRow state="selected">
          <TableCell>Priya Nair</TableCell>
          <TableCell>priya@acme.com</TableCell>
          <TableCell>Admin</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>Sam Whitfield</TableCell>
          <TableCell>sam@acme.com</TableCell>
          <TableCell>Member</TableCell>
        </TableRow>
      </Table>

      <Inline gap="sm">
        <Button variant="secondary">Export</Button>
        <Button>Invite member</Button>
      </Inline>
    </Stack>
  );
}
