import {PLUGIN_DUMP_VERSION} from './types.js';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {filledPathsIssue} from '../../scripts/contract-schema.js';import {createFigmaMock} from '../../scripts/plugin-engine-mock-figma.mjs';
const script=readFileSync(new URL('./dump.plugin.js',import.meta.url),'utf8');
const read=vm.runInNewContext(script.slice(script.indexOf('function dumpHostVectorStrokeGeometry('),script.indexOf('// Native usage drawings:'))+';dumpHostVectorStrokeGeometry',{filledPathsIssue});
const source=JSON.parse(readFileSync(new URL('./fixtures/host-stroke-geometry/SOURCE.json',import.meta.url),'utf8'));
const plain=(x:any)=>JSON.parse(JSON.stringify(x));
test('actual native inside strokes retain centered outline, fill mask and exact owner without mutation',()=>{
 for(const row of source.rows){const node={...row.child,type:'VECTOR'},target={nodeId:node.id,instanceId:row.id,componentId:row.mainId,instancePath:[],childPath:[0]},before=JSON.stringify(node),r=plain(read(node,target));assert.deepEqual(r.fillGeometry,node.fillGeometry);assert.deepEqual(r.centeredStrokeGeometry,node.strokeGeometry);assert.equal(r.strokeAlign,'INSIDE');assert.equal(r.strokeWeight,1);assert.equal(r.strokeMiterLimit,node.strokeMiterLimit);assert.deepEqual(r.target,target);assert.equal(JSON.stringify(node),before);assert(r.centeredStrokeGeometry[0].data.includes('-1'),'centered outline extends beyond the fill and needs alignment clipping');}
});
test('missing or malformed native stroke facts never manufacture an outline',()=>{
 const n={...source.rows[0].child,type:'VECTOR'},target={nodeId:n.id,instanceId:'i',componentId:'c',instancePath:[],childPath:[0]};
 assert.equal(read(n,undefined),undefined);
 for(const change of [{strokeMiterLimit:undefined},{strokeMiterLimit:0},{strokeJoin:'UNKNOWN'},{strokeCap:'UNKNOWN'},{opacity:2},{fillGeometry:[]},{strokeGeometry:[]},{strokeWeight:NaN},{strokeAlign:'UNKNOWN'},{relativeTransform:[[1,0,Infinity],[0,1,0]]},{dashPattern:[-1]},{width:0},{strokeGeometry:[{data:'bad',windingRule:'NONZERO'}]}])assert.throws(()=>read({...n,...change},target));
 const unknown={...n};Object.defineProperty(unknown,'strokeGeometry',{get(){throw Error('API unavailable')}});assert.throws(()=>read(unknown,target),/unavailable/);
});
test('canonical dump attaches stroke geometry and independent solid paint to the overridden descendant',async()=>{
 const {figma:mock}=createFigmaMock({consumerVariableModes:true}),figma:any=mock;const main=figma.createComponent();main.name='Mark';const instance=main.createInstance();const vector=figma.createRectangle();vector.type='VECTOR';instance.appendChild(vector);
 Object.assign(vector,source.rows[0].child,{id:vector.id,name:'Vector',type:'VECTOR',fills:[{type:'SOLID',color:{r:1,g:0,b:0},opacity:1,blendMode:'NORMAL'}],strokes:[{type:'SOLID',color:{r:0,g:0,b:1},opacity:1,blendMode:'NORMAL'}]});
 const collection=figma.variables.createVariableCollection('Paints'),fill=figma.variables.createVariable('Fill',collection,'COLOR'),stroke=figma.variables.createVariable('Stroke',collection,'COLOR');fill.setValueForMode(collection.modes[0].modeId,{r:1,g:0,b:0,a:1});stroke.setValueForMode(collection.modes[0].modeId,{r:0,g:0,b:1,a:1});vector.fills[0].boundVariables={color:{type:'VARIABLE_ALIAS',id:fill.id}};vector.strokes[0].boundVariables={color:{type:'VARIABLE_ALIAS',id:stroke.id}};
 instance.overrides=[{id:vector.id,overriddenFields:['fills','strokes','strokeStyleId']}];const parent=figma.createComponent();parent.name='HostStroke';parent.appendChild(instance);figma.currentPage.appendChild(main);figma.currentPage.appendChild(parent);
 const src=script.replace(/^const TARGET_SETS = \[[^\n]*\];$/m,'const TARGET_SETS = ["HostStroke"];');const capture=async()=>plain(await vm.runInNewContext(`(async()=>{${src}\n})()`,{figma,console:{log(){},warn(){},error(){}}}));const dump=await capture();
 const h=dump.HostStroke.variants[0].children[0].hostOverrides[0];assert.deepEqual(h.fields,['fills','strokes','strokeStyleId']);assert.equal(h.vectorStrokeGeometry.strokeAlign,'INSIDE');assert.deepEqual(h.vectorStrokeGeometry.target,h.solidStrokeTarget);assert.deepEqual(h.sourceNormalStrokeComposition.paint.color,{r:0,g:0,b:1});assert.deepEqual(h.sourceNormalFillComposition.paint.color,{r:1,g:0,b:0});assert.equal(dump._provenance.dumpVersion,PLUGIN_DUMP_VERSION);assert.equal(h.variableConsumers[fill.id].name,'Fill');assert.equal(h.variableConsumers[stroke.id].name,'Stroke');assert.notEqual(h.sourceNormalFillComposition.variableId,h.sourceNormalStrokeComposition.variableId);
 vector.strokeGeometry=[];const partial=await capture(),missing=partial.HostStroke.variants[0].children[0].hostOverrides[0];assert.equal(missing.vectorStrokeGeometry,undefined);assert(missing.stroke);assert.deepEqual(missing.fields,h.fields);assert(partial._degradations.some((d:any)=>d.code==='host-vector-stroke-geometry-unavailable'));
});
