/**
 * CSS/DOM CONFORMANCE FIXTURE — the report generator.
 *
 *   npm run conformance:report        writes conformance/EXPECTATIONS.md
 *
 * EXPECTATIONS.md is the LIVING CAPABILITY MATRIX. `docs/FIGMA-CAPABILITY-MATRIX.md`
 * is 355 hand-written lines asserting what the engine does, referenced by
 * nothing and checked by nothing; this file asserts nothing — every row is a
 * measurement against a hand-authored expectation, and the gate refuses to
 * agree with it unless the measurement still holds.
 *
 * Deterministic: same artifacts → identical bytes.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { DISPOSITIONS, HERE, loadCases } from './build.js';
import { measureAll, summarize, RED_VERDICTS, type Measured } from './run.js';

const esc = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

const VERDICT_MARK: Record<string, string> = {
  PASS: '🟢',
  'SILENT-LOSS': '🔴',
  'RUN-ABORTED': '🔴',
  'UNDECLARED-CARRY': '🔴',
  'WRONG-NAME': '🔴',
  UNMEASURED: '🔴',
  'UNMEASURED-YELLOW': '🟡',
};

export function renderReport(rows: Measured[]): string {
  const cases = loadCases();
  const byId = new Map(cases.map((c) => [c.id, c]));
  const counts = summarize(rows);
  const red = RED_VERDICTS.reduce((n, v) => n + counts[v], 0);
  const unsupported = rows.filter((r) => r.expect === 'UNSUPPORTED').length;
  const L: string[] = [];

  L.push('# CSS/DOM conformance — EXPECTATIONS');
  L.push('');
  L.push('*GENERATED by `npm run conformance:report`. Do not edit — edit the case');
  L.push('directories under `conformance/cases/` and re-run.*');
  L.push('');
  L.push('This is the **living capability matrix**: what the computed-capture pipeline');
  L.push('does with each CSS/DOM construct, measured rather than asserted. Every row is a');
  L.push('synthetic case whose expected disposition was declared **in advance**, in a');
  L.push('manifest that is deliberately independent of the engine — not derived from');
  L.push('`isFusable`, `styled`, `DECLARED_CHANNELS`, `CHANNEL_TO_COMPUTED`,');
  L.push('`TOKEN_CHANNELS` or `carriedParts`. A construct that is neither carried nor');
  L.push('named-refused is a hard failure here, where in every other instrument in this');
  L.push('repo it is simply absent from the denominator and scores 100%.');
  L.push('');
  L.push('## The numbers');
  L.push('');
  L.push('| | |');
  L.push('|---|---|');
  L.push(`| cases | **${rows.length}** |`);
  L.push(`| 🟢 pass | **${counts.PASS}** |`);
  L.push(`| 🔴 red | **${red}** |`);
  L.push(`| 🟡 yellow (UNSUPPORTED, never read) | **${counts['UNMEASURED-YELLOW']}** |`);
  L.push(
    `| **UNSUPPORTED declared — THE RATCHET** | **${unsupported}** · may only DECREASE without an explicit manifest edit |`,
  );
  L.push('');
  L.push('Declared dispositions: ' + DISPOSITIONS.map((d) => `${d} ${rows.filter((r) => r.expect === d).length}`).join(' · ') + '.');
  L.push('');
  L.push('**A green gate here would mean the cases are too easy.** The point of the');
  L.push('fixture is a measured frontier, and every red below is an open, named defect —');
  L.push('recorded in `conformance/BASELINE.json` so it cannot drift in either direction:');
  L.push('a new red is a regression, and a red that becomes green must be re-recorded, so');
  L.push('a fix can never be absorbed silently.');
  L.push('');

  // ---- the red sections, most dangerous first ------------------------------
  const section = (
    title: string,
    blurb: string[],
    pick: (r: Measured) => boolean,
  ): void => {
    const group = rows.filter(pick);
    if (group.length === 0) return;
    L.push(`## ${title} — ${group.length}`);
    L.push('');
    for (const b of blurb) L.push(b);
    L.push('');
    for (const r of group) {
      const c = byId.get(r.id)!;
      L.push(`### \`${r.id}\``);
      L.push('');
      L.push(`- **construct** — \`${esc(r.construct)}\``);
      L.push(`- **why it matters** — ${esc(c.why)}`);
      L.push(`- **declared** ${r.expect}${r.expectName ? ` by the name \`${esc(r.expectName)}\` in ${esc(c.expectWhere)}` : ''}`);
      L.push(
        `- **measured** — channel \`${esc(r.channel)}\`; observed ${r.measured ? `on ${r.observedOn.map((p) => `\`${p}\``).join(', ')}` : '**NOWHERE** — the reader never recorded it'}; ` +
          `carried ${r.carried ? `as ${r.carriedAs.map((s) => `\`${esc(s)}\``).join(', ')}` : '**not at all**'}`,
      );
      L.push(`- **canvas** — ${r.canvas}: ${esc(c.canvas.note)}`);
      L.push(`- **verdict** — ${VERDICT_MARK[r.verdict]} **${r.verdict}**: ${esc(r.note)}`);
      if (r.namingQuote) L.push(`- **what the engine actually said** — \`${esc(r.namingQuote.slice(0, 400))}\``);
      L.push('');
    }
  };

  section(
    'SILENT-LOSS 🔴',
    [
      'The class the fixture exists to catch, and the only one that is **never waivable**.',
      'The construct is observable in `captured-truth.json`, absent from the contract, and',
      'named by no string in the union of `LEDGER.md`, the receipt/refusal arrays of',
      '`enriched.extension.json`, `review-queue.json`, `source-bindings.json.skips`,',
      '`scorecard.json` `namedLosses`, and the run\'s stdout. The pipeline read the fact,',
      'dropped it, and said nothing.',
    ],
    (r) => r.verdict === 'SILENT-LOSS',
  );

  section(
    'RUN-ABORTED 🔴',
    [
      'The production runner **threw** on this case and wrote no artifacts. The refusal is',
      'loud and precisely named — but it is a whole-round stop, not a per-construct',
      'receipt. A real library that ships this construct on one component cannot be',
      'onboarded at all, and the failure gives no way to proceed past it.',
    ],
    (r) => r.verdict === 'RUN-ABORTED',
  );

  section(
    'UNDECLARED-CARRY (HARMFUL) 🔴',
    [
      'The engine carried a construct the manifest says has **no canvas spelling**. The',
      'doctrine calls UNDECLARED-CARRY "good news, wrong manifest" — and usually it is.',
      'It is not, when the thing carried cannot be drawn: then the carriage is the defect',
      'and the manifest was right. Fixing these means changing the engine, not the',
      'manifest.',
    ],
    (r) => r.verdict === 'UNDECLARED-CARRY' && r.harmful,
  );

  section(
    'UNDECLARED-CARRY 🔴',
    [
      'Good news, wrong manifest: the engine carries more than the manifest declared. The',
      'remedy is to **update the manifest** — which is how this capability matrix stays',
      'true instead of drifting into fiction.',
    ],
    (r) => r.verdict === 'UNDECLARED-CARRY' && !r.harmful,
  );

  section(
    'WRONG-NAME 🔴',
    [
      'The loss is named — by a message that does not distinguish this construct from any',
      'other. This is the condition that hid Carbon\'s hollow checkbox: two constructs',
      'collapsing into one indistinguishable receipt.',
    ],
    (r) => r.verdict === 'WRONG-NAME',
  );

  section(
    'UNMEASURED 🔴',
    ['Declared CARRIED/LOWERED (or REFUSED-by-name) and the reader never looked. A refusal claim about a fact that was never read is unfounded.'],
    (r) => r.verdict === 'UNMEASURED',
  );

  section(
    'UNMEASURED 🟡 — the reader never looked',
    [
      '"We never read `::marker`" and "we read it and refused it" are different facts and',
      'get different colours. These are counted, not waived: each is a hole in the reader,',
      'and the count is part of the ratchet.',
    ],
    (r) => r.verdict === 'UNMEASURED-YELLOW',
  );

  // ---- the full frontier table --------------------------------------------
  L.push('## The frontier — every case');
  L.push('');
  L.push('| | case | feature | construct | declared | measured | verdict |');
  L.push('|---|---|---|---|---|---|---|');
  for (const r of [...rows].sort((a, b) => (a.feature + a.id).localeCompare(b.feature + b.id))) {
    const measured = r.aborted
      ? 'run aborted'
      : !r.measured
        ? 'not read'
        : r.carried
          ? 'carried'
          : r.namedByExpectName
            ? 'refused, by name'
            : r.namedAtAll
              ? 'refused, other name'
              : 'dropped, unnamed';
    L.push(
      `| ${VERDICT_MARK[r.verdict]} | \`${r.id}\` | ${esc(r.feature)} | \`${esc(r.construct)}\` | ${r.expect} | ${measured} | ${r.verdict} |`,
    );
  }
  L.push('');

  L.push('## What this round cannot yet test');
  L.push('');
  L.push('Named, not skipped:');
  L.push('');
  L.push('- **Animation.** An infinite `@keyframes` animation is the most common motion');
  L.push('  construct in any design system (spinners), and it cannot enter this fixture');
  L.push('  without risking the double-run byte-identity self-check for the WHOLE round.');
  L.push('  The capture pins infinite animations at `currentTime 0`; that pin is exactly');
  L.push('  what a conformance case should measure, and measuring it needs a per-case');
  L.push('  determinism budget the harness does not have.');
  L.push('- **The canvas half.** Every `canvas:` field in the manifest is a DECLARATION,');
  L.push('  not a measurement: nothing in this round runs the emitted Figma script and');
  L.push('  checks that a construct declared PRESENT actually reaches a node. Until it');
  L.push('  does, "carried" means "reached the contract", not "reached the canvas".');
  L.push('- **State planes and axes.** Every case is one combo with no variant axes, so');
  L.push('  per-state and per-axis correlation — where the MUI and Carbon rounds found');
  L.push('  most of their defects — is untested here.');
  L.push('- **Multi-viewport.** `media-non-matching` proves a non-matching branch is');
  L.push('  invisible; it cannot prove what a second capture at a second viewport would');
  L.push('  do, because the fixture pins one viewport.');
  L.push('- **The three RUN-ABORTED cases** measure nothing downstream of the abort: their');
  L.push('  carriage, naming and canvas behaviour are unknown, not absent.');
  L.push('');
  L.push('---');
  L.push('');
  L.push('*Measured against `extract/computed/out/conformance/` — the UNMODIFIED');
  L.push('`extract/computed` pipeline over `conformance/conformance.config.json`. No engine');
  L.push('code path special-cases the fixture.*');
  L.push('');
  return L.join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.join(HERE, 'report.ts')) {
  const rows = measureAll();
  const md = renderReport(rows);
  writeFileSync(path.join(HERE, 'EXPECTATIONS.md'), md);
  console.log(`conformance/EXPECTATIONS.md — ${rows.length} cases, ${md.split('\n').length} lines`);
}
