/**
 * CANVAS → CODE, the shared plan — what a proposal from the canvas turns
 * into on the code side, and the honest sentence about how much that code
 * can be trusted.
 *
 * The loop (task #40) has two ends that must say the SAME thing:
 *   - the plugin's Send tab, which shows a designer the files their
 *     proposal would create BEFORE they create them, and
 *   - `ds-contracts propose-pr`, which actually writes those files into the
 *     pull request next to the contract.
 * Both read this module, so the file list and the provenance sentence can
 * never drift apart. Pure and browser-safe (no node:*): the plugin engine
 * bundles it, the CLI imports it.
 *
 * THE ASYMMETRY IS THE POINT. A component set this tool GENERATED carries a
 * `ds_contracts/contractId` marker; canvas → contract → code is then a true
 * round trip and the emitters reproduce the component byte for byte. A
 * HAND-BUILT set carries no such marker: the proposal is an INVERSION of
 * what could be read off the canvas, so the emitted component is a starting
 * point, not a reproduction. Nothing in this repo may blur those two.
 *
 * Path naming mirrors core/emitter.ts (the registry emitters) and
 * scripts/generate-components.ts (the shipping react layout). That mirroring
 * is a receipt, not a hope: scripts/plugin-engine-check.mjs runs the real
 * emitters over a real contract and asserts their paths equal these.
 */
import { kebab } from './naming.js';

/** How the design side came to be — the fact that decides the sentence. */
export type CanvasProvenance =
  /** The set carries a ds_contracts/contractId marker: this tool drew it. */
  | 'tool-generated'
  /** No marker: a human drew it, and the contract is an inversion. */
  | 'hand-built'
  /** No canvas provenance was recorded (e.g. a contract document straight
   *  out of the repo). Never guessed into one of the two above. */
  | 'unrecorded';

/** Human labels for the built-in emit targets (the registry's `label`s,
 *  shortened for a 640px plugin panel). */
export const CODE_TARGET_LABELS: Record<string, string> = {
  react: 'React + CSS Modules',
  html: 'Static HTML + CSS',
  'react-inline': 'React, inline styles',
  'figma-script': 'Figma sync script',
};

export interface CodePathOptions {
  /** react only: emit <Name>.stories.tsx (the CLI's --stories). */
  stories?: boolean;
}

/**
 * The files a target writes for ONE contract, relative to the output root.
 *
 * The react target's root barrel (`index.ts` listing every component) is
 * DELIBERATELY absent: it describes the whole library, and a proposal knows
 * exactly one component — committing it would clobber the repo's barrel down
 * to a single line. Callers say so out loud; see propose-pr.
 *
 * An unregistered target returns [] — the caller must name it as unknown
 * rather than invent a file list.
 */
export function plannedCodePaths(
  contractName: string,
  target: string,
  opts: CodePathOptions = {},
): string[] {
  const slug = kebab(contractName);
  switch (target) {
    case 'react':
      return [
        `${contractName}/${contractName}.module.css`,
        `${contractName}/${contractName}.tsx`,
        ...(opts.stories ? [`${contractName}/${contractName}.stories.tsx`] : []),
        `${contractName}/index.ts`,
      ];
    case 'html':
      return [`${slug}.html`, `${slug}.css`];
    case 'react-inline':
      return [`${contractName}.inline.tsx`];
    case 'figma-script':
      return [`${slug}.figma.js`];
    default:
      return [];
  }
}

/** The non-negotiable provenance sentence. Printed in the PR body and shown
 *  in the plugin BEFORE the proposal leaves the canvas. */
export function provenanceSentence(p: CanvasProvenance): string {
  switch (p) {
    case 'tool-generated':
      return (
        'This component set was GENERATED by ds-contracts (it carries a ds_contracts/contractId marker), ' +
        'so canvas → contract → code is a true round trip: re-running the emitters reproduces the component ' +
        'byte for byte from the contract in this PR.'
      );
    case 'hand-built':
      return (
        'This component set was HAND-BUILT — ds-contracts did not draw it, so the contract is an INVERSION of ' +
        'what could be read off the canvas. The generated component is a STARTING POINT, NOT A REPRODUCTION: ' +
        'review it as new code, and expect anything the canvas could not state to be missing.'
      );
    case 'unrecorded':
      return (
        'No canvas provenance was recorded for this contract (it did not arrive as a CONTRACT-PROPOSAL from the ' +
        "plugin's Send tab), so this PR cannot say whether the design was tool-generated or hand-built. The " +
        'generated code is a projection of the contract as written — nothing here claims it matches a canvas.'
      );
  }
}

/** One-line version for a cramped surface (the plugin panel). */
export function provenanceHeadline(p: CanvasProvenance): string {
  switch (p) {
    case 'tool-generated':
      return 'Round trip — this set was generated from a contract, so the code comes back byte for byte.';
    case 'hand-built':
      return 'Inversion — this set was hand-built, so the code is a starting point, not a reproduction.';
    case 'unrecorded':
      return 'Provenance not recorded — the code is a projection of the contract, nothing more.';
  }
}

export interface CodePlan {
  target: string;
  targetLabel: string;
  /** Output-root-relative paths, in write order. */
  paths: string[];
}

// ---------------------------------------------------------------------------
// Proposal file naming — ONE spelling for both delivery doors.
//
// These used to live only in packages/cli/src/commands/figma.ts, so the
// plugin's GitHub PR door could not name the files `figma receive` /
// `propose-pr` write without copying the rule (and drifting). They are pure
// and browser-safe, so they live here now; the CLI re-exports them.
// ---------------------------------------------------------------------------

/** Flatten an untrusted contract id into one safe filename stem: every
 *  character outside the schema's own id alphabet is replaced, path separators
 *  included, so the result is always a single flat filename. */
export const flatIdStem = (id: string, fallback: string): string =>
  id
    .normalize('NFKC')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/\.\.+/g, '.')
    .replace(/^[.-]+|[.-]+$/g, '') || fallback;

/** id → <name>.contract.json (the prefix segment stripped) — the filename
 *  `figma receive` and `propose-pr` both give a contract, main or stub. */
export const contractFileNameForId = (id: string): string =>
  `${flatIdStem(id.replace(/^[^.]+\./, ''), 'stub')}.contract.json`;

/** Proposal artifacts retain valid ids verbatim for backward-compatible
 * filenames, while hostile ids collapse to one flat basename. */
export const proposalFileNameForId = (id: string): string =>
  `${flatIdStem(id, 'proposal')}.proposal.json`;

/** The minted DTCG sidecar's filename — the same stem propose-pr derives
 *  (`proposalFileNameForId` minus its suffix) so both doors write the
 *  provisional token tree to the SAME place. */
export const mintedTokensFileNameForId = (contractId: string): string =>
  `${flatIdStem(contractId, 'proposal')}.minted.dtcg.json`;

/** The whole answer to "what code would this proposal produce?" — one entry
 *  per target, plus the sentence. Shared by the plugin panel and the CLI. */
export function canvasCodePlan(
  contractName: string,
  targets: string[],
  opts: CodePathOptions = {},
): CodePlan[] {
  return targets.map((target) => ({
    target,
    targetLabel: CODE_TARGET_LABELS[target] ?? target,
    paths: plannedCodePaths(contractName, target, opts),
  }));
}
