/**
 * DRAFT capture-config generation — the runtime-styled onboarding ramp (G6).
 *
 *   npm run extract:draft-config   [-- path/to/extract.config.json [--out <file>]]
 *   ds-contracts extract --draft-capture-config
 *
 * Today an Emotion/Tailwind-style library needs a hand-authored
 * extract/computed/configs/<lib>.json — expert work (docs/17 names it; the
 * MUI and Tailwind PROVENANCE files document multi-hour pipelines). This
 * module drafts that config FROM the static extract pass: the react-tsx/cem
 * adapters already enumerate components and enum props, so the component
 * list, axes, sampleText, stateProps for the two inferable state booleans
 * (disabled/checked), and the stage/browser/enumeration defaults are filled
 * mechanically. Everything the static pass CANNOT know — classAllow grammar,
 * varPrefix, mount recipe, fixedProps, callback stubs — gets an EXPLICIT
 * `"__review:*"` marker with one-line guidance, never a guessed value.
 *
 * ACK DISCIPLINE (draft ≠ approved): the draft carries a top-level
 * `"__unreviewed-draft"` marker and the capture runner
 * (extract/computed/capture.ts loadConfig) REFUSES any config carrying it,
 * by name. A human reviews every marker, deletes the top-level marker, and
 * only then does the config capture — the same explicit-ack rule the
 * resolver's decisions ledger enforces (docs/16: assist writes proposals,
 * only explicit acks write anything load-bearing).
 *
 * PURE CORE + thin shell: draftCaptureConfig() is a pure function of the
 * extraction — same input, byte-same draft (unit-pinned in
 * packages/cli/test/draft-capture-config.test.ts).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { loadConfig, outDir } from './config.js';
import { kebab } from './types.js';
import { AXIS_BY_BOOL_PROP, boolAxisValueMap } from './bool-axis-props.js';
import type { ExtractedComponent } from './types.js';

export const DRAFT_MARKER_KEY = '__unreviewed-draft';

/** B.16 (docs/23) — the drafted `enumeration.unsetLabel`. This label is the
 *  pseudo-value a DEFAULTLESS enum axis enumerates, and fusion mints it into
 *  token paths — so it MUST be token-ref-legal (letters/digits/./-). The old
 *  default was the sentinel "__unset": its underscores violated the token-ref
 *  grammar and fusion died with ~40 "must be brace-wrapped" errors that never
 *  named the underscore. The sentinel never ships again. */
export const DRAFT_UNSET_LABEL = 'unset';

export const DRAFT_MARKER_MESSAGE =
  'DRAFT capture config, machine-generated from the static extract pass. Review every "__review:*" ' +
  'field (they mark what the tool could NOT infer), fix the values, DELETE each marker you have ' +
  'reviewed, then delete THIS key. The capture runner refuses any config still carrying this key — ' +
  'draft is not approved.';

export const draftRefusalMessage = (configPath: string): string =>
  `${configPath} is an UNREVIEWED DRAFT capture config (top-level "${DRAFT_MARKER_KEY}" marker). ` +
  'A draft never captures: review every "__review:*" field (classAllow, varPrefix, mount, ' +
  'stateProps, fixedProps, …), then delete the marker to approve it. Generated by ' +
  '`ds-contracts extract --draft-capture-config` / `npm run extract:draft-config`.';

export interface DraftOptions {
  /** npm package name of the library under capture (cwd package.json when the
   *  shell can read it; null = review marker). */
  libraryPackage: string | null;
  libraryVersion: string | null;
  /** Repo-relative dir where the static pass wrote proposed contracts —
   *  ComponentConfig.contract points into it. */
  contractsDir: string;
  /** DTCG token files (ExtractConfig.tokens) — prefills tokens.dtcg. */
  tokensDtcg: string[];
}

export interface DraftResult {
  config: Record<string, unknown>;
  /** Count of "__review:*" markers in the draft — the human's checklist size. */
  reviewFields: number;
  components: number;
}

/** The two boolean props whose contract state is inferable BY NAME — the
 *  visual-parity state vocabulary. Everything else is a review item, not a
 *  guess. */
// `checked` is NOT here on purpose: it selects a rendering, so it is a
// variant axis (AXIS_BY_BOOL_PROP), never a pseudo-class state. The runner
// refuses a `checked` state by name; the drafter used to emit exactly that.
const STATE_BY_BOOL_PROP: Record<string, string> = { disabled: 'disabled' };

const countReviewFields = (node: unknown): number => {
  if (Array.isArray(node)) return node.reduce((n: number, v) => n + countReviewFields(v), 0);
  if (node && typeof node === 'object') {
    return Object.entries(node).reduce(
      (n, [k, v]) => n + (k.startsWith('__review') ? 1 : 0) + countReviewFields(v),
      0,
    );
  }
  return 0;
};

/** PURE: static extraction → draft CaptureConfig JSON. Deterministic — the
 *  extraction is already name-sorted and every emitted key is derived. */
export function draftCaptureConfig(extracted: ExtractedComponent[], opts: DraftOptions): DraftResult {
  const components = extracted.map((c) => {
    const enumProps = c.props.filter((p) => p.kind === 'enum' && p.values && p.values.length > 0);
    const boolProps = c.props.filter((p) => p.kind === 'boolean');
    const stateProps = boolProps
      .filter((p) => STATE_BY_BOOL_PROP[p.name] !== undefined)
      .map((p) => ({ prop: p.name, state: STATE_BY_BOOL_PROP[p.name] }));
    const axisBools = boolProps.filter((p) => AXIS_BY_BOOL_PROP[p.name] !== undefined);
    const unmappedBools = boolProps.filter(
      (p) => STATE_BY_BOOL_PROP[p.name] === undefined && AXIS_BY_BOOL_PROP[p.name] === undefined,
    );
    const requiredNonAxis = c.props.filter(
      (p) => !p.optional && (p.kind === 'string' || p.kind === 'number' || p.kind === 'node'),
    );
    const eventProps = c.props.filter((p) => p.kind === 'event');
    const numericAxes = enumProps.filter((p) => p.values!.every((v) => /^-?\d+(\.\d+)?$/.test(v)));

    const entry: Record<string, unknown> = {
      name: c.name,
      importName: c.name,
      contract: `${opts.contractsDir}/${kebab(c.name)}.contract.json`,
      sampleText: c.name,
      axes: [...enumProps.map((p) => p.name), ...axisBools.map((p) => p.name)],
    };
    if (stateProps.length > 0) entry.stateProps = stateProps;
    // A rendering-selecting boolean (checked) mounts as a variant axis: the
    // seed contract carries it as an enum (extract/propose.ts, same table)
    // and the config maps each label back to the boolean the library takes.
    if (axisBools.length > 0) {
      entry.axisValueMap = Object.fromEntries(axisBools.map((p) => [p.name, boolAxisValueMap(p.name)]));
    }
    if (unmappedBools.length > 0) {
      entry['__review:stateProps'] = `boolean prop(s) ${unmappedBools.map((p) => p.name).join(', ')} — if one is a pseudo-class plane the same instance takes (hover/active/focus-visible/disabled), add {"prop","state"} here; if it SELECTS a rendering (checked-like), model it under "axes" + "axisValueMap" and as an enum in the contract; otherwise pin it under fixedProps or leave it at its default`;
    }
    if (requiredNonAxis.length > 0) {
      entry['__review:fixedProps'] = `required prop(s) ${requiredNonAxis.map((p) => p.name).join(', ')} — pin each to a deterministic value ("fixedProps": {"${requiredNonAxis[0].name}": "…"}); an unpinned required prop makes every mount fail or drift`;
    }
    if (eventProps.length > 0) {
      entry['__review:callbackProps'] = `function prop(s) ${eventProps.map((p) => p.name).join(', ')} — list any the library REQUIRES at mount under "callbackProps" (each is stubbed to () => {})`;
    }
    if (numericAxes.length > 0) {
      entry['__review:axisValueMap'] = `axis value(s) of ${numericAxes.map((p) => p.name).join(', ')} look numeric — if the library expects numbers (not strings), map them: "axisValueMap": {"${numericAxes[0].name}": {"${numericAxes[0].values![0]}": ${numericAxes[0].values![0]}}}`;
    }
    // B.16 — DEFAULTLESS ENUM AXES: pick a REAL base value (the first enum
    // value) and mark it for review, like every other non-inferable pick.
    // Without a contract default the capture pins the base combo to the
    // unset pseudo-value, and that label is minted into token paths — the
    // old "__unset" sentinel shipped underscores straight into the token-ref
    // grammar and killed fusion two stages later.
    const defaultlessAxes = enumProps.filter((p) => p.default === undefined);
    if (defaultlessAxes.length > 0) {
      entry.baseCombo = Object.fromEntries(
        defaultlessAxes.map((p) => [p.name, String(p.values![0])]),
      );
      entry['__review:baseCombo'] = `enum axis(es) ${defaultlessAxes.map((p) => p.name).join(', ')} declare no default — baseCombo pins each to its FIRST enum value so the base combo mounts a real value; review each pick (or add a default to the contract). A defaultless axis still enumerates an extra "${DRAFT_UNSET_LABEL}" pseudo-value plane (enumeration.unsetLabel), and that label becomes a token-path segment — keep it token-ref-legal (letters/digits/./- only; the old "__unset" sentinel broke fusion by name of the brace-wrap rule, never the underscore)`;
    }
    return entry;
  });

  const library: Record<string, unknown> = {
    package: opts.libraryPackage ?? '',
    version: opts.libraryVersion ?? '',
    framework: 'react',
    classPrefix: '',
  };
  if (opts.libraryPackage === null || opts.libraryVersion === null) {
    library['__review:package'] =
      'package/version could not be read from a package.json — the capture harness must have EXACTLY this package@version installed (the runner refuses version drift)';
  } else {
    library['__review:version'] = `detected from package.json, NOT confirmed — the harness must carry ${opts.libraryPackage}@${opts.libraryVersion} exactly (the runner refuses version drift)`;
  }
  library['__review:classPrefix'] =
    'CSS class prefix stripped for part naming/signatures (Polaris uses "Polaris-"); "" keeps full class names';
  library['__review:classAllow'] =
    'OPTIONAL regex of class names KEPT in captured signatures — required for hashed/atomic class systems (StyleX keeps only its stable per-component class; Tailwind uses "^$" to keep none); absent keeps every class (CSS-Modules behavior)';
  library['__review:varPrefix'] =
    'OPTIONAL custom-property prefix for the CSS-vars source-binding reader ("--mui-" for Emotion cssVariables themes, "--" for Tailwind v4); absent = reader off — pixels stay correct, token NAMES degrade to literals (docs/16 graceful degradation)';

  const config: Record<string, unknown> = {
    [DRAFT_MARKER_KEY]: DRAFT_MARKER_MESSAGE,
    library,
    mount: {
      imports: [],
      // A FRAGMENT, not '' — the harness template interpolates these around
      // the mounted component, and empty strings emit INVALID JSX that kills
      // esbuild with the opaque "Expected } but found ." two stages later
      // (walked live, 2026-08-03). Every committed config uses a fragment or a
      // provider; the draft now starts from the shape that compiles.
      wrapperOpen: '<>',
      wrapperClose: '</>',
      '__review:mount':
        'the mount recipe the library needs on EVERY stage — stylesheet import (Tailwind: the built CSS, inlined by the harness), ThemeProvider/locale wrappers (MUI: createTheme({cssVariables:true})); see extract/computed/configs/{mui,tailwind}.json for worked examples',
    },
    tokens: {
      dtcg: opts.tokensDtcg,
      css: '',
      '__review:tokens':
        'dtcg prefilled from the extract config (empty = none found — build a DTCG token file first); "css" must point at the stylesheet that defines those tokens as custom properties',
    },
    browser: { viewport: { width: 900, height: 1000 }, deviceScaleFactor: 1, colorScheme: 'light' },
    stage: { width: 320, height: 96, padding: 16 },
    enumeration: { cartesianLimit: 512, unsetLabel: DRAFT_UNSET_LABEL },
    components,
  };
  return { config, reviewFields: countReviewFields(config), components: components.length };
}

// ---------------------------------------------------------------------------
// Shell — `tsx extract/draft-capture-config.ts [extract.config.json] [--out f]`
// Filename-matched (the extract/run.ts convention) so bundling never triggers.
// ---------------------------------------------------------------------------
export function runDraftCaptureConfig(configArg?: string, outArg?: string): string {
  const { config, from } = loadConfig(configArg);
  const out = outDir(config);
  const extractionPath = path.join(out, 'code-extraction.json');
  if (!existsSync(extractionPath)) {
    throw new Error(
      `${extractionPath} not found — run the static pass first (\`ds-contracts extract\` / \`npm run extract:code\`); the draft is generated FROM it, never from guesses.`,
    );
  }
  const extracted = JSON.parse(readFileSync(extractionPath, 'utf8')) as ExtractedComponent[];
  let libraryPackage: string | null = null;
  let libraryVersion: string | null = null;
  if (existsSync('package.json')) {
    const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as { name?: string; version?: string };
    libraryPackage = typeof pkg.name === 'string' ? pkg.name : null;
    libraryVersion = typeof pkg.version === 'string' ? pkg.version : null;
  }
  const draft = draftCaptureConfig(extracted, {
    libraryPackage,
    libraryVersion,
    contractsDir: `${out}/contracts`,
    tokensDtcg: config.tokens ?? [],
  });
  const outPath = outArg ?? path.join(out, 'capture-config.draft.json');
  writeFileSync(outPath, JSON.stringify(draft.config, null, 2) + '\n');
  console.log(
    `✔ DRAFT capture config → ${outPath}  (config: ${from})\n` +
      `  ${draft.components} component(s) prefilled (axes from enum props, disabled/checked stateProps, stage/browser defaults)\n` +
      `⚠ ${draft.reviewFields} "__review:*" field(s) need a human — classAllow/varPrefix/mount/fixedProps are NOT inferable from static source\n` +
      `  The capture runner REFUSES this file until the top-level "${DRAFT_MARKER_KEY}" marker is deleted (draft ≠ approved).\n` +
      `  When approved: ds-contracts extract --computed --config ${outPath} --harness <sandbox dir>`,
  );
  return outPath;
}

if (process.argv[1] && /extract[\\/]draft-capture-config\.(m?[tj]s)$/.test(path.resolve(process.argv[1]))) {
  const argv = process.argv.slice(2);
  const outIdx = argv.indexOf('--out');
  const outArg = outIdx > -1 ? argv[outIdx + 1] : undefined;
  const positionals = argv.filter((a, i) => !a.startsWith('--') && argv[i - 1] !== '--out');
  runDraftCaptureConfig(positionals[0], outArg);
}
