/**
 * The product spine on a library the recipe path never taught: the role map
 * is DRAFTED from the ledger with evidence, the fixture is PROPOSED with zero
 * invented leaves, and a leaf the ledger cannot carry REFUSES the proposal
 * until a person gives it with evidence.
 */
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import { Ledger } from "./ledger.js";
import { draftCheckboxRoles } from "./draft-roles.js";
import { proposeCheckboxFixture, type GlyphSpec } from "./propose-fixture.js";
import type { CheckboxRoles } from "./schema-checkbox.js";

const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");
const LEDGER = "extract/computed/out/chakra/checkbox/captured-truth.json";
const GLYPH: GlyphSpec = JSON.parse(readFileSync(path.join(REPO, "recipe/evidence/pointed/checkbox-chakra/glyph.json"), "utf8"));
const DASH = {
  "dash.width": { value: "9.9167", why: "checkmark.js indeterminate stroke lowered to a rounded rect" },
  "dash.height": { value: "1.75", why: "stroke-width 3 × 14/24" },
  "dash.radius": { value: "0.875", why: "round caps" },
};

test("the role map is drafted from what the parts DO, with evidence, and matches the reviewed map", () => {
  const draft = draftCheckboxRoles(new Ledger(REPO, LEDGER));
  assert.deepEqual(draft.unresolved, []);
  assert.equal(draft.roles.glyphPath, "tag:polyline");
  assert.equal(draft.roles.box, draft.roles.hit, "Chakra's control is its own hit area");
  assert.equal(draft.roles.row, "root");
  assert.equal(draft.evidence.box!.confidence, "high");
  assert.match(draft.evidence.label!.why, /"Accept"/);
  assert.match(draft.evidence.glyphPath!.why, /polyline's points are not a computed channel/);
});

test("a proposal reads every leaf from the ledger or a named review — and invents nothing", () => {
  const roles = draftCheckboxRoles(new Ledger(REPO, LEDGER)).roles as CheckboxRoles;
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "checkbox.chakra.ts"));
  const result = proposeCheckboxFixture({ library: "chakra", ledger: LEDGER, roles, glyph: GLYPH, sets: DASH, out });
  assert.deepEqual(result.refused, []);
  const counts = { ledger: 0, set: 0, spelling: 0 };
  for (const l of Object.values(result.proposal.leaves)) counts[l.from] += 1;
  assert.deepEqual(counts, { ledger: 42, set: 3, spelling: 10 });
  assert.equal(result.proposal.content.label, "Accept");
  assert.equal(result.proposal.typography.family, "Inter");
  assert.equal(result.proposal.glyph.scaled.strokeWidth, 1.75, "stroke scaled from viewBox units onto the 14px box");
  const module = readFileSync(result.modulePath, "utf8");
  assert.ok(module.includes("GENERATED by recipe/fixture-reader/propose-fixture.ts"));
  assert.ok(module.includes('"box.size": 20, // ledger'), "every read leaf names its ledger key");
  assert.ok(module.includes("reviewed: checkmark.js indeterminate"), "every reviewed leaf names its evidence");
});

test("a leaf the ledger cannot carry REFUSES the proposal by name until given with evidence", () => {
  const roles = draftCheckboxRoles(new Ledger(REPO, LEDGER)).roles as CheckboxRoles;
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "checkbox.chakra.ts"));
  const result = proposeCheckboxFixture({ library: "chakra", ledger: LEDGER, roles, glyph: GLYPH, sets: {}, out });
  // The stroked <path> has width/height "auto" — unreadable as px — while its
  // border-top-left-radius reads a genuine 0px; so two leaves refuse and the
  // radius would be taken from the ledger (which is why the reviewed run
  // supplies all three with the lowering's arithmetic).
  assert.equal(result.refused.length, 2);
  assert.ok(result.refused.every((r) => /^dash\.(width|height):/.test(r)), result.refused.join("\n"));
  assert.ok(result.refused[0]!.includes("--set dash.width"), "the refusal says how to satisfy it");
});
