/**
 * The product spine on a library the recipe path never taught: the role map
 * is DRAFTED from the ledger with evidence, the fixture is PROPOSED with zero
 * invented leaves, and a leaf the ledger cannot carry REFUSES the proposal
 * until a person gives it with evidence.
 */
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import { Ledger } from "./ledger.js";
import { draftCheckboxRoles } from "./draft-roles.js";
import { proposeCheckboxFixture, type GlyphSpec } from "./propose-fixture.js";
import type { CheckboxRoles } from "./schema-checkbox.js";

const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");
const LEDGER = "extract/computed/out/chakra/checkbox/captured-truth.json";
const GLYPH: GlyphSpec = JSON.parse(readFileSync(path.join(REPO, "recipe/evidence/pointed/checkbox-chakra/glyph.json"), "utf8"));
const DASH = {
  "dash.width": { value: "9.9167", why: "checkmark.js indeterminate stroke lowered to a rounded rect" },
  "dash.height": { value: "1.75", why: "stroke-width 3 × 14/24" },
  "dash.radius": { value: "0.875", why: "round caps" },
};

test("the role map is drafted from what the parts DO, with evidence, and matches the reviewed map", () => {
  const draft = draftCheckboxRoles(new Ledger(REPO, LEDGER));
  assert.deepEqual(draft.unresolved, []);
  assert.equal(draft.roles.glyphPath, "tag:polyline");
  assert.equal(draft.roles.box, draft.roles.hit, "Chakra's control is its own hit area");
  assert.equal(draft.roles.row, "root");
  assert.equal(draft.evidence.box!.confidence, "high");
  assert.match(draft.evidence.label!.why, /"Accept"/);
  assert.match(draft.evidence.glyphPath!.why, /polyline's points are not a computed channel/);
});

test("a proposal reads every leaf from the ledger or a named review — and invents nothing", () => {
  const roles = draftCheckboxRoles(new Ledger(REPO, LEDGER)).roles as CheckboxRoles;
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "checkbox.chakra.ts"));
  const result = proposeCheckboxFixture({ library: "chakra", ledger: LEDGER, roles, glyph: GLYPH, sets: DASH, out });
  assert.deepEqual(result.refused, []);
  const counts = { ledger: 0, set: 0, spelling: 0 };
  for (const l of Object.values(result.proposal.leaves)) counts[l.from] += 1;
  assert.deepEqual(counts, { ledger: 43, set: 3, spelling: 10 });
  assert.equal(result.proposal.content.label, "Accept");
  assert.equal(result.proposal.typography.family, "Inter");
  assert.equal(result.proposal.glyph.scaled.strokeWidth, 1.75, "stroke scaled from viewBox units onto the 14px box");
  const module = readFileSync(result.modulePath, "utf8");
  assert.ok(module.includes("GENERATED by recipe/fixture-reader/propose-fixture.ts"));
  assert.ok(module.includes('"box.size": 20, // ledger'), "every read leaf names its ledger key");
  assert.ok(module.includes("reviewed: checkmark.js indeterminate"), "every reviewed leaf names its evidence");
});

test("a leaf the ledger cannot carry REFUSES the proposal by name until given with evidence", () => {
  const roles = draftCheckboxRoles(new Ledger(REPO, LEDGER)).roles as CheckboxRoles;
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "checkbox.chakra.ts"));
  const result = proposeCheckboxFixture({ library: "chakra", ledger: LEDGER, roles, glyph: GLYPH, sets: {}, out });
  // The stroked <path> has width/height "auto" — unreadable as px — while its
  // border-top-left-radius reads a genuine 0px; so two leaves refuse and the
  // radius would be taken from the ledger (which is why the reviewed run
  // supplies all three with the lowering's arithmetic).
  assert.equal(result.refused.length, 2);
  assert.ok(result.refused.every((r) => /^dash\.(width|height):/.test(r)), result.refused.join("\n"));
  assert.ok(result.refused[0]!.includes("--set dash.width"), "the refusal says how to satisfy it");
});

import { draftSwitchRoles } from "./draft-roles.js";
import { SWITCH_SPELLINGS, switchSchemaMappings, type SwitchComboMap, type SwitchRoles } from "./schema-switch.js";
import { evaluate } from "./propose-fixture.js";
import { tokenLeaves } from "./reader.js";

test("switch@1: drafted roles + combos re-derive MUI's hand-written fixture with zero disagreement on every readable leaf", async () => {
  const ledger = new Ledger(REPO, "extract/computed/out/mui/switch/captured-truth.json");
  const draft = draftSwitchRoles(ledger);
  assert.deepEqual(draft.unresolved, []);
  assert.equal(draft.combos["false.enabled"], "primary.medium.unchecked.enabled", "combos come from the declared base, not a name guess");
  assert.equal(draft.roles.thumbInsideTrack, false, "MUI's thumb is a sibling of the track → opacity baked into the fill");
  assert.equal(draft.roles.travelOn, "idx:0", "the SwitchBase carries the travel transform");
  const fixtures = (await import("../fixtures/library-switches.js")) as Record<string, unknown>;
  const config = fixtures.muiSwitchAdapterConfig as { tokens: Record<string, unknown> };
  const hand = tokenLeaves(config.tokens);
  const evaluated = evaluate(ledger, switchSchemaMappings(draft.roles as SwitchRoles, { combos: draft.combos as SwitchComboMap }), new Map(), SWITCH_SPELLINGS);
  let agree = 0, differ: string[] = [];
  for (const [path, leaf] of Object.entries(evaluated.leaves)) {
    if (leaf.from !== "ledger" || !hand.has(path)) continue;
    const h = hand.get(path)!;
    const eq = typeof h === "number" && typeof leaf.value === "number" ? Math.abs(h - leaf.value) <= 0.01 : String(h).toLowerCase() === String(leaf.value).toLowerCase();
    if (eq) agree += 1; else differ.push(`${path}: schema ${leaf.value} vs hand ${h}`);
  }
  assert.deepEqual(differ, []);
  // 18 parameter leaves are readable on a bare MUI mount (the rest are the
  // label the mount has none of); rederive.ts also compares the string
  // extras (rowAlign, thumbShadow, clips) and reports 21.
  assert.ok(agree >= 18, `only ${agree} leaves agreed`);
});

test("switch@1: AntD's knob is a pseudo-element with a real shadow, and the travel is an inset difference", () => {
  const ledger = new Ledger(REPO, "extract/computed/out/antd/switch/captured-truth.json");
  const draft = draftSwitchRoles(ledger);
  assert.equal(draft.roles.thumbPseudo, "::before");
  assert.equal(draft.roles.travelInset, "left");
  const evaluated = evaluate(ledger, switchSchemaMappings(draft.roles as SwitchRoles, { combos: draft.combos as SwitchComboMap }), new Map(), SWITCH_SPELLINGS);
  assert.equal(evaluated.leaves["thumb.travel"]?.value, 22);
  assert.equal(evaluated.leaves["track.padding"]?.value, 2, "the handle's inset is the track padding");
  assert.match(String(evaluated.leaves["thumbShadow"]?.value), /rgba\(0, 35, 11, 0\.2\) 0px 2px 4px/, "the handleShadow the hand table missed");
});

test("switch@1: a capture with no checked axis is refused, not guessed (Astryx)", () => {
  const draft = draftSwitchRoles(new Ledger(REPO, "extract/computed/out/astryx-core/switch/captured-truth.json"));
  assert.ok(draft.unresolved.length >= 2, draft.unresolved.join("\n"));
  assert.ok(draft.unresolved.some((u) => /true\.enabled/.test(u)));
});

test("a BARE control (shadcn: no label part, oklch colours) proposes the label-less cell and invents nothing", () => {
  const ledgerRel = "extract/computed/out/shadcn/checkbox/captured-truth.json";
  const draft = draftCheckboxRoles(new Ledger(REPO, ledgerRel));
  assert.deepEqual(draft.unresolved, [], "a missing label is evidence, not a refusal");
  assert.equal(draft.roles.label, undefined);
  const gap = "shadcn's indeterminate state renders the check glyph — a named gap";
  const sets = {
    "dash.width": { value: "0", why: gap }, "dash.height": { value: "0", why: gap }, "dash.radius": { value: "0", why: gap },
    "states.indeterminate.enabled.dashFill": { value: "#00000000", why: gap }, "states.indeterminate.disabled.dashFill": { value: "#00000000", why: gap },
  };
  const glyph = { path: "M20 6 L9 17 L4 12", viewBox: 24, paint: "stroke" as const, strokeWidth: 2, cap: "round" as const, join: "round" as const, source: "lucide-react@1.30.0 dist/esm/icons/check.mjs" };
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "checkbox.shadcn.ts"));
  const result = proposeCheckboxFixture({ library: "shadcn", ledger: ledgerRel, roles: draft.roles as CheckboxRoles, glyph, sets, out });
  assert.deepEqual(result.refused, []);
  assert.equal(result.proposal.content.label, null, "the bare cell");
  assert.equal(result.proposal.leaves["states.checked.enabled.boxFill"]?.value, "#171717ff", "oklch(0.205 0 0) by CSS Color 4, pinned to the render's (23,23,23)");
  assert.equal(result.proposal.leaves["states.unchecked.enabled.boxBorder"]?.value, "#e5e5e5ff", "oklch(0.922 0 0) → 229");
  assert.equal(result.proposal.leaves["labelFontSize"]?.from, "spelling");
  assert.match(String(result.proposal.leaves["boxShadow"]?.value), /rgba\(0, 0, 0, 0\.05\) 0px 1px 2px 0px$/, "shadow-xs read from the box");
  const module = readFileSync(result.modulePath, "utf8");
  assert.ok(module.includes("bareLabelFont()"), "the generated module carries the inert label font");
  assert.ok(module.includes('{"label":null}'), "content.label null");
});

import { draftSwitchRoles } from "./draft-roles.js";
import { proposeSwitchFixture } from "./propose-switch.js";
import type { SwitchComboMap, SwitchRoles } from "./schema-switch.js";

test("switch@1 proposes MUI's bare mount: the label-less cell, the handle shadow, 0 invented", () => {
  const ledgerRel = "extract/computed/out/mui/switch/captured-truth.json";
  const draft = draftSwitchRoles(new Ledger(REPO, ledgerRel));
  assert.deepEqual(draft.unresolved, []);
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "switch.mui.ts"));
  const r = proposeSwitchFixture({ library: "mui", ledger: ledgerRel, roles: draft.roles as SwitchRoles, combos: draft.combos as SwitchComboMap, sets: {}, out, unsupported: ["hover"] });
  assert.deepEqual(r.refused, []);
  assert.equal(r.proposal.content.label, null);
  assert.equal(r.proposal.leaves["thumb.travel"]?.value, 20);
  assert.match(String(r.proposal.leaves["thumbShadow"]?.value), /^rgba\(0, 0, 0, 0\.2\) 0px 2px 1px -1px/);
  assert.equal(r.proposal.leaves["hitClips"]?.value, "true", "Switch-root overflow hidden, read");
  const counts = { ledger: 0, set: 0, spelling: 0 }; for (const l of Object.values(r.proposal.leaves)) counts[l.from] += 1;
  assert.deepEqual(counts, { ledger: 21, set: 0, spelling: 13 });
  const module = readFileSync(r.modulePath, "utf8");
  assert.ok(module.includes("bareLabelFont()") && module.includes("refusal-interaction-hover"), "bare font + refusals named from the capture");
});

test("switch@1 proposes shadcn: a pill radius in exponent notation and a calc(100% - 2px) travel of the thumb's own width", () => {
  const ledgerRel = "extract/computed/out/shadcn/switch/captured-truth.json";
  const draft = draftSwitchRoles(new Ledger(REPO, ledgerRel));
  assert.deepEqual(draft.unresolved, []);
  assert.equal(draft.roles.travelChannel, "translate");
  const dir = mkdtempSync(path.join(tmpdir(), "point-"));
  const out = path.relative(REPO, path.join(dir, "switch.shadcn.ts"));
  const r = proposeSwitchFixture({ library: "shadcn", ledger: ledgerRel, roles: draft.roles as SwitchRoles, combos: draft.combos as SwitchComboMap, sets: {}, out, unsupported: ["hover"] });
  assert.deepEqual(r.refused, []);
  assert.equal(r.proposal.leaves["thumb.travel"]?.value, 14, "calc(100% - 2px) of a 16px thumb");
  assert.equal(r.proposal.leaves["track.radius"]?.value, 33554400, "3.35544e+07px, Chromium's clamp of rounded-full");
  assert.equal(r.proposal.leaves["states.true.enabled.trackFill"]?.value, "#171717ff");
  assert.equal(r.proposal.content.label, null);
});

import { draftAvatarRoles } from "./draft-roles.js";
import { proposeAvatarFixture } from "./propose-avatar.js";
import type { AvatarRoles } from "./schema-avatar.js";

test("avatar@1 proposes a held-out library (Altitude) and MUI's own capture with nothing invented", () => {
  for (const [lib, expect] of [["altitude", { height: 40, radius: 20, initials: "AB", fill: "#f4f3f1ff" }], ["mui", { height: 40, radius: 20, initials: "A", fill: "#bdbdbdff" }]] as const) {
    const ledgerRel = `extract/computed/out/${lib}/avatar/captured-truth.json`;
    const draft = draftAvatarRoles(new Ledger(REPO, ledgerRel));
    assert.deepEqual(draft.unresolved, [], lib);
    const dir = mkdtempSync(path.join(tmpdir(), "point-"));
    const out = path.relative(REPO, path.join(dir, `avatar.${lib}.ts`));
    const r = proposeAvatarFixture({ library: lib, ledger: ledgerRel, roles: draft.roles as AvatarRoles, combo: draft.combo!, sets: {}, out, unsupported: ["hover"] });
    assert.deepEqual(r.refused, [], lib);
    assert.equal(r.proposal.leaves["box.height"]?.value, expect.height, lib);
    assert.equal(r.proposal.leaves["box.radius"]?.value, expect.radius, `${lib}: a 50% radius is half the box`);
    assert.equal(r.proposal.leaves["rest.boxFill"]?.value, expect.fill, lib);
    assert.equal(r.proposal.content.label, expect.initials, lib);
    const counts = { ledger: 0, set: 0, spelling: 0 }; for (const l of Object.values(r.proposal.leaves)) counts[l.from] += 1;
    assert.deepEqual(counts, { ledger: 13, set: 0, spelling: 1 }, lib);
  }
});

import { draftTooltipRoles } from "./draft-roles.js";
import { proposeTooltipFixture } from "./propose-tooltip.js";
import type { TooltipRoles } from "./schema-tooltip.js";

test("tooltip@1 proposes AntD's tip (shadow, placement and arrow named as refusals from the capture) and MUI's (line-height normal → auto)", () => {
  for (const [lib, expect] of [["antd", { paddingX: 8, radius: 6, unit: "px", text: "Tooltip text", refusals: ["refusal-box-shadow", "refusal-placement", "refusal-arrow"] }], ["mui", { paddingX: 8, radius: 4, unit: "auto", text: "Tooltip text", refusals: ["refusal-placement"] }]] as const) {
    const ledgerRel = `extract/computed/out/${lib}/tooltip/captured-truth.json`;
    const draft = draftTooltipRoles(new Ledger(REPO, ledgerRel));
    assert.deepEqual(draft.unresolved, [], lib);
    const dir = mkdtempSync(path.join(tmpdir(), "point-"));
    const out = path.relative(REPO, path.join(dir, `tooltip.${lib}.ts`));
    const r = proposeTooltipFixture({ library: lib, ledger: ledgerRel, roles: draft.roles as TooltipRoles, combo: draft.combo!, sets: {}, out, unsupported: ["placement"] });
    assert.deepEqual(r.refused, [], lib);
    assert.equal(r.proposal.leaves["box.paddingX"]?.value, expect.paddingX, lib);
    assert.equal(r.proposal.leaves["box.radius"]?.value, expect.radius, lib);
    assert.equal(r.proposal.leaves["lineHeightUnit"]?.value, expect.unit, lib);
    assert.equal(r.proposal.leaves["box.height"]?.from, "spelling", `${lib}: the tip hugs`);
    assert.equal(r.proposal.content.label, expect.text, lib);
    const module = readFileSync(r.modulePath, "utf8");
    for (const id of expect.refusals) assert.ok(module.includes(id), `${lib}: ${id} named from the capture`);
  }
});

import { draftChipRoles, draftLinkRoles } from "./draft-roles.js";
import { proposeChipFixture } from "./propose-chip.js";
import { proposeLinkFixture } from "./propose-link.js";
import type { ChipRoles } from "./schema-chip.js";
import type { LinkRoles } from "./schema-link.js";

test("chip@1 proposes MUI's chip (the label span's padding is part of the inset) and Carbon's Tag (--capture tag)", () => {
  for (const [lib, capture, expect] of [["mui", "chip", { paddingX: 12, height: 32, label: "idx:0" }], ["carbon", "tag", { paddingX: 8, height: 24, label: "idx:0" }]] as const) {
    const ledgerRel = `extract/computed/out/${lib}/${capture}/captured-truth.json`;
    const draft = draftChipRoles(new Ledger(REPO, ledgerRel));
    assert.deepEqual(draft.unresolved, [], lib);
    assert.equal(draft.roles.label, expect.label, `${lib}: the text part is a child of the box`);
    const dir = mkdtempSync(path.join(tmpdir(), "point-"));
    const r = proposeChipFixture({ library: lib, ledger: ledgerRel, roles: draft.roles as ChipRoles, combo: draft.combo!, sets: {}, out: path.relative(REPO, path.join(dir, `chip.${lib}.ts`)), unsupported: ["hover"] });
    assert.deepEqual(r.refused, [], lib);
    assert.equal(r.proposal.leaves["box.paddingX"]?.value, expect.paddingX, `${lib}: box padding + label padding`);
    assert.equal(r.proposal.leaves["box.height"]?.value, expect.height, lib);
  }
});

test("link@1 proposes Altitude's link (underline read) and MUI's at the always-underlined combo", () => {
  for (const [lib, expect] of [["altitude", { decoration: "underline", unit: "px", combo: "unset" }], ["mui", { decoration: "underline", unit: "auto", combo: "primary.always" }]] as const) {
    const ledgerRel = `extract/computed/out/${lib}/link/captured-truth.json`;
    const draft = draftLinkRoles(new Ledger(REPO, ledgerRel));
    assert.deepEqual(draft.unresolved, [], lib);
    assert.equal(draft.combo, expect.combo, lib);
    const dir = mkdtempSync(path.join(tmpdir(), "point-"));
    const r = proposeLinkFixture({ library: lib, ledger: ledgerRel, roles: draft.roles as LinkRoles, combo: draft.combo!, sets: {}, out: path.relative(REPO, path.join(dir, `link.${lib}.ts`)), unsupported: ["hover"] });
    assert.deepEqual(r.refused, [], lib);
    assert.equal(r.proposal.leaves["decoration"]?.value, expect.decoration, lib);
    assert.equal(r.proposal.leaves["lineHeightUnit"]?.value, expect.unit, lib);
    assert.equal(r.proposal.leaves["box.height"]?.from, "spelling", `${lib}: the link hugs`);
  }
});

import { draftTabsRoles } from "./draft-roles.js";
import { proposeTabsFixture } from "./propose-tabs.js";
import type { TabsRoles } from "./schema-tabs.js";

test("tabs@1 drafts MUI's indicator bar, Carbon's bottom-border indicator, and refuses shadcn's filled tab by name", () => {
  const mui = draftTabsRoles(new Ledger(REPO, "extract/computed/out/mui/tabs/captured-truth.json"));
  assert.deepEqual(mui.unresolved, []); assert.ok(mui.roles.indicator, "MUI has an indicator part");
  const carbon = draftTabsRoles(new Ledger(REPO, "extract/computed/out/carbon/tabs/captured-truth.json"));
  assert.deepEqual(carbon.unresolved, []); assert.equal(carbon.roles.indicatorIsBorder, true, "Carbon's indicator is the selected tab's bottom border, not its 1px hidden buttons");
  assert.equal(carbon.combo, "", "a capture with no axes has the empty combo");
  const shadcn = draftTabsRoles(new Ledger(REPO, "extract/computed/out/shadcn/tabs/captured-truth.json"));
  assert.equal(shadcn.unresolved.length, 1); assert.match(shadcn.unresolved[0]!, /indicator: no absolute painted bar/);
  for (const [lib, draft, expect] of [["mui", mui, { height: 2, fill: "#1976d2ff", textCase: "upper", selected: "Overview" }], ["carbon", carbon, { height: 2, fill: "#0f62feff", textCase: "original", selected: "Overview" }]] as const) {
    const dir = mkdtempSync(path.join(tmpdir(), "point-"));
    const r = proposeTabsFixture({ library: lib, ledger: `extract/computed/out/${lib}/tabs/captured-truth.json`, roles: draft.roles as TabsRoles, combo: draft.combo!, sets: {}, out: path.relative(REPO, path.join(dir, `tabs.${lib}.ts`)), unsupported: ["hover"] });
    assert.deepEqual(r.refused, [], lib);
    assert.equal(r.proposal.leaves["indicator.height"]?.value, expect.height, lib);
    assert.equal(r.proposal.leaves["indicator.fill"]?.value, expect.fill, lib);
    assert.equal(r.proposal.leaves["textCase"]?.value, expect.textCase, lib);
    assert.equal(r.proposal.content.selected, expect.selected, lib);
  }
});
