if(figma.fileKey!=="byMp6lt0Ij9b2QbkDGFwBh")throw new Error("WRONG-FILE:"+figma.fileKey);
if(figma.root.name!=="Scratch Project")throw new Error("WRONG-FILE-NAME:"+figma.root.name);
const NS="ds.contracts.checkbox.recipe.v1";
const runIdentity="548cf953-a473aa6a-ff3a8565-checkbox-v3";
const pageName="Recipe Pivot / Checkbox / 548cf953-a473aa6a-ff3a8565-checkbox-v3";
const adapterIdentity="mui-checkbox-reviewed-v1";
const recipeHash="a473aa6a174bc1074fd1586c85c7dff9d89721af6064f82d5959a167d6e79d82";
const envelopeHash="fa0686892b9546fe819b7e9e80c31f2c7aae11a6a61eb1d20140ce329d67798a";
const signed=["115:295378","163:35981","183:70641","183:69150","85:6781","173:48924","181:64873","183:74742","183:75031","183:75302","183:75495","183:76022","196:76370","197:76679","197:76903","198:77048","198:77177"];
await figma.loadAllPagesAsync();
const page=figma.root.children.find(p=>p.name===pageName);
if(!page)throw new Error("CHECKBOX-PAGE-MISSING");
if(signed.includes(page.id))throw new Error("CHECKBOX-MUST-NOT-WRITE-SIGNED-PAGE:"+page.id);
if(page.getSharedPluginData(NS,"runIdentity")!==runIdentity)throw new Error("CHECKBOX-PAGE-IDENTITY-MISMATCH:"+page.id);
await figma.setCurrentPageAsync(page);
if(page.children.some(n=>n.type==="SECTION"&&n.getSharedPluginData(NS,"adapterIdentity")===adapterIdentity))throw new Error("CHECKBOX-SECTION-EXISTS:"+adapterIdentity);
if(page.children.some(n=>n.name==="Component Container"))throw new Error("CHECKBOX-PAGE-LEVEL-COMPONENT-CONTAINER");
const hex=v=>({r:parseInt(v.slice(1,3),16)/255,g:parseInt(v.slice(3,5),16)/255,b:parseInt(v.slice(5,7),16)/255,a:parseInt(v.slice(7,9),16)/255});
const paint=v=>{const c=hex(v);return{type:"SOLID",color:{r:c.r,g:c.g,b:c.b},opacity:c.a};};
const allFonts=await figma.listAvailableFontsAsync();
const fontSpec={"requestedFamily":"Roboto","requestedStyle":"Regular","resolvedFamily":"Roboto","resolvedStyle":"Regular","resolution":"requested","fallbackChain":[{"family":"Roboto","style":"Regular"},{"family":"Helvetica","style":"Regular"},{"family":"Arial","style":"Regular"}]};
const found=fontSpec.fallbackChain.map(c=>allFonts.find(f=>f.fontName.family===c.family&&f.fontName.style===c.style)).find(Boolean);
if(!found)throw new Error("CHECKBOX-FONT-UNAVAILABLE:"+fontSpec.requestedFamily);
if(found.fontName.family!==fontSpec.resolvedFamily||found.fontName.style!==fontSpec.resolvedStyle)throw new Error("CHECKBOX-FONT-PROVENANCE-TAMPER:"+found.fontName.family);
await figma.loadFontAsync(found.fontName);
const collectionName="Recipe Checkbox / "+runIdentity+" / "+adapterIdentity;
const locals=figma.variables.getLocalVariableCollectionsAsync?await figma.variables.getLocalVariableCollectionsAsync():[];
if(locals.some(c=>c.name===collectionName))throw new Error("CHECKBOX-VARIABLE-COLLECTION-COLLISION:"+collectionName);
const collection=figma.variables.createVariableCollection(collectionName);
collection.renameMode(collection.modes[0].modeId,"Default");
collection.hiddenFromPublishing=true;
const modeId=collection.modes[0].modeId;
const prefix="mui.checkbox";
const planned=[["FLOAT","mui.checkbox.wrapper-size",42],["FLOAT","mui.checkbox.box-size",24],["FLOAT","mui.checkbox.box-radius",2],["FLOAT","mui.checkbox.box-borderWidth",2],["FLOAT","mui.checkbox.box-padding",9],["FLOAT","mui.checkbox.row-gap",0],["FLOAT","mui.checkbox.dash-width",10],["FLOAT","mui.checkbox.dash-height",2],["FLOAT","mui.checkbox.dash-radius",0],["FLOAT","mui.checkbox.check-width",24],["FLOAT","mui.checkbox.check-height",24],["FLOAT","mui.checkbox.check-strokeWidth",0],["FLOAT","mui.checkbox.labelFontSize",16],["COLOR","mui.checkbox.states-unchecked-enabled-boxFill","#00000000"],["COLOR","mui.checkbox.states-unchecked-enabled-boxBorder","#00000099"],["COLOR","mui.checkbox.states-unchecked-enabled-label","#000000de"],["COLOR","mui.checkbox.states-unchecked-enabled-dashFill","#00000000"],["COLOR","mui.checkbox.states-unchecked-enabled-checkFill","#ffffffff"],["COLOR","mui.checkbox.states-unchecked-disabled-boxFill","#00000000"],["COLOR","mui.checkbox.states-unchecked-disabled-boxBorder","#00000042"],["COLOR","mui.checkbox.states-unchecked-disabled-label","#00000061"],["COLOR","mui.checkbox.states-unchecked-disabled-dashFill","#00000000"],["COLOR","mui.checkbox.states-unchecked-disabled-checkFill","#ffffffff"],["COLOR","mui.checkbox.states-checked-enabled-boxFill","#ffffffff"],["COLOR","mui.checkbox.states-checked-enabled-boxBorder","#00000000"],["COLOR","mui.checkbox.states-checked-enabled-label","#000000de"],["COLOR","mui.checkbox.states-checked-enabled-dashFill","#00000000"],["COLOR","mui.checkbox.states-checked-enabled-checkFill","#1976d2ff"],["COLOR","mui.checkbox.states-checked-disabled-boxFill","#ffffffff"],["COLOR","mui.checkbox.states-checked-disabled-boxBorder","#00000000"],["COLOR","mui.checkbox.states-checked-disabled-label","#00000061"],["COLOR","mui.checkbox.states-checked-disabled-dashFill","#00000000"],["COLOR","mui.checkbox.states-checked-disabled-checkFill","#00000042"],["COLOR","mui.checkbox.states-indeterminate-enabled-boxFill","#1976d2ff"],["COLOR","mui.checkbox.states-indeterminate-enabled-boxBorder","#1976d2ff"],["COLOR","mui.checkbox.states-indeterminate-enabled-label","#000000de"],["COLOR","mui.checkbox.states-indeterminate-enabled-dashFill","#ffffffff"],["COLOR","mui.checkbox.states-indeterminate-enabled-checkFill","#ffffffff"],["COLOR","mui.checkbox.states-indeterminate-disabled-boxFill","#00000042"],["COLOR","mui.checkbox.states-indeterminate-disabled-boxBorder","#00000042"],["COLOR","mui.checkbox.states-indeterminate-disabled-label","#00000061"],["COLOR","mui.checkbox.states-indeterminate-disabled-dashFill","#ffffffff"],["COLOR","mui.checkbox.states-indeterminate-disabled-checkFill","#ffffffff"]];
const vars=new Map();
for(const [type,identity,value] of planned){
  const name="token/"+(type==="COLOR"?"color":"float")+"/id-"+Array.from(identity).map(ch=>ch.charCodeAt(0).toString(16).padStart(2,"0")).join("");
  const variable=figma.variables.createVariable(name,collection,type);
  variable.scopes=["ALL_SCOPES"];
  variable.setValueForMode(modeId,type==="COLOR"?hex(value):value);
  vars.set(type+":"+identity,variable);
}
const bindColor=(base,identity)=>figma.variables.setBoundVariableForPaint(base,"color",vars.get("COLOR:"+identity));
const bindFloat=(node,field,identity)=>node.setBoundVariable(field,vars.get("FLOAT:"+identity));
const geom={"wrapper":42,"box":24,"radius":2,"border":2,"padding":9,"gap":0,"dash":{"w":10,"h":2,"r":0},"check":{"path":"M19 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.11 0 2-.9 2-2V5c0-1.1-.89-2-2-2zm-9 14l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z","w":24,"h":24,"stroke":0,"paint":"fill","winding":"EVENODD","cap":"NONE","join":"MITER","rotation":0,"placement":"center"},"fontSize":16,"lineHeightUnit":"AUTO","lineHeight":0,"rowAlign":"CENTER","cells":{"unchecked/false":{"box":"#00000000","border":"#00000099","op":1,"label":"#000000de","dash":"#00000000","check":"#ffffffff"},"unchecked/true":{"box":"#00000000","border":"#00000042","op":1,"label":"#00000061","dash":"#00000000","check":"#ffffffff"},"checked/false":{"box":"#ffffffff","border":"#00000000","op":1,"label":"#000000de","dash":"#00000000","check":"#1976d2ff"},"checked/true":{"box":"#ffffffff","border":"#00000000","op":1,"label":"#00000061","dash":"#00000000","check":"#00000042"},"indeterminate/false":{"box":"#1976d2ff","border":"#1976d2ff","op":1,"label":"#000000de","dash":"#ffffffff","check":"#ffffffff"},"indeterminate/true":{"box":"#00000042","border":"#00000042","op":1,"label":"#00000061","dash":"#ffffffff","check":"#ffffffff"}}};
let paintedFont=found.fontName;
const paintLabel=async()=>{
  const label=figma.createText();
  label.fontName=paintedFont;
  label.characters="Accept terms";
  label.fontSize=geom.fontSize;
  label.lineHeight=geom.lineHeightUnit==="PIXELS"?{unit:"PIXELS",value:geom.lineHeight}:{unit:"AUTO"};
  label.textAlignHorizontal="LEFT";
  label.textAlignVertical="CENTER";
  label.textAutoResize="WIDTH_AND_HEIGHT";
  if(label.characters.trim().length>0&&(label.width<=0||label.absoluteRenderBounds===null)){
    let ok=false;
    for(const candidate of fontSpec.fallbackChain){
      if(candidate.family===fontSpec.resolvedFamily&&candidate.style===fontSpec.resolvedStyle)continue;
      const next=allFonts.find(e=>e.fontName.family===candidate.family&&e.fontName.style===candidate.style);
      if(!next)continue;
      await figma.loadFontAsync(next.fontName);
      label.fontName=next.fontName;
      label.characters="Accept terms";
      if(label.width>0&&label.absoluteRenderBounds){paintedFont=next.fontName;ok=true;break;}
    }
    if(!ok&&(label.width<=0||label.absoluteRenderBounds===null))throw new Error("CHECKBOX-FONT-ZERO-INTRINSIC");
  }
  if(label.width<=0||label.height<=0)throw new Error("CHECKBOX-TEXT-GEOMETRY");
  return label;
};
let nextX=0;
for(const child of page.children){if(child.type==="SECTION")nextX=Math.max(nextX,child.x+child.width+240);}
const section=figma.createSection();
section.name="Recipe Pivot / MUI / "+recipeHash.slice(0,8);
section.x=nextX;section.y=0;page.appendChild(section);
section.setSharedPluginData(NS,"adapterIdentity",adapterIdentity);
section.setSharedPluginData(NS,"recipeHash",recipeHash);
section.setSharedPluginData(NS,"variableCollectionId",collection.id);
const components=[];
for(const checked of ["unchecked","checked","indeterminate"]){
  for(const disabled of ["false","true"]){
    const arm=disabled==="true"?"disabled":"enabled";
    const cell=geom.cells[checked+"/"+disabled];
    const component=figma.createComponent();
    component.clipsContent=false;
    component.name="Checked="+checked+", Disabled="+disabled;
    component.layoutMode="HORIZONTAL";
    component.primaryAxisAlignItems="MIN";
    component.counterAxisAlignItems=geom.rowAlign;
    component.itemSpacing=geom.gap;
    component.fills=[];
    bindFloat(component,"itemSpacing",prefix+".row-gap");
    section.appendChild(component);
    const hit=figma.createFrame();
    hit.name="checkbox/hit";
    hit.layoutMode="HORIZONTAL";
    hit.primaryAxisAlignItems="CENTER";
    hit.counterAxisAlignItems="CENTER";
    hit.itemSpacing=0;
    hit.fills=[];
    hit.clipsContent=false;
    hit.paddingTop=geom.padding;hit.paddingRight=geom.padding;hit.paddingBottom=geom.padding;hit.paddingLeft=geom.padding;
    hit.resizeWithoutConstraints(geom.wrapper,geom.wrapper);
    hit.layoutSizingHorizontal="FIXED";hit.layoutSizingVertical="FIXED";
    bindFloat(hit,"width",prefix+".wrapper-size");
    bindFloat(hit,"height",prefix+".wrapper-size");
    component.appendChild(hit);
    const box=figma.createFrame();
    box.name="checkbox/box";
    box.layoutMode="HORIZONTAL";
    box.primaryAxisAlignItems="CENTER";
    box.counterAxisAlignItems="CENTER";
    box.itemSpacing=0;
    box.opacity=cell.op;
    box.clipsContent=true;
    box.resizeWithoutConstraints(geom.box,geom.box);
    box.layoutSizingHorizontal="FIXED";box.layoutSizingVertical="FIXED";
    box.fills=[bindColor(paint(cell.box),prefix+".states-"+checked+"-"+arm+"-boxFill")];
    box.strokes=[bindColor(paint(cell.border),prefix+".states-"+checked+"-"+arm+"-boxBorder")];
    box.strokeWeight=geom.border;box.strokeAlign="INSIDE";
    box.topLeftRadius=geom.radius;box.topRightRadius=geom.radius;box.bottomRightRadius=geom.radius;box.bottomLeftRadius=geom.radius;
    bindFloat(box,"width",prefix+".box-size");
    bindFloat(box,"height",prefix+".box-size");
    bindFloat(box,"strokeWeight",prefix+".box-borderWidth");
    bindFloat(box,"topLeftRadius",prefix+".box-radius");
    bindFloat(box,"topRightRadius",prefix+".box-radius");
    bindFloat(box,"bottomRightRadius",prefix+".box-radius");
    bindFloat(box,"bottomLeftRadius",prefix+".box-radius");
    hit.appendChild(box);
    const dash=figma.createFrame();
    dash.name="checkbox/glyph/dash";
    dash.visible=checked==="indeterminate";
    dash.layoutMode="HORIZONTAL";
    dash.resizeWithoutConstraints(geom.dash.w,geom.dash.h);
    dash.layoutSizingHorizontal="FIXED";dash.layoutSizingVertical="FIXED";
    dash.fills=[bindColor(paint(cell.dash),prefix+".states-"+checked+"-"+arm+"-dashFill")];
    dash.strokes=[];
    dash.effects=[];
    dash.topLeftRadius=geom.dash.r;dash.topRightRadius=geom.dash.r;dash.bottomRightRadius=geom.dash.r;dash.bottomLeftRadius=geom.dash.r;
    bindFloat(dash,"width",prefix+".dash-width");
    bindFloat(dash,"height",prefix+".dash-height");
    box.appendChild(dash);
    const vector=figma.createVector();
    vector.name="checkbox/glyph/check";
    vector.visible=checked==="checked";
    vector.vectorPaths=[{windingRule:geom.check.winding,data:geom.check.path}];
    vector.strokeCap=geom.check.cap;
    vector.strokeJoin=geom.check.join;
    vector.rotation=0;
    vector.effects=[];
    if(geom.check.paint==="stroke"){
      vector.fills=[];
      vector.strokes=[bindColor(paint(cell.check),prefix+".states-"+checked+"-"+arm+"-checkFill")];
      vector.strokeWeight=geom.check.stroke;
      vector.strokeAlign="CENTER";
      bindFloat(vector,"strokeWeight",prefix+".check-strokeWidth");
    }else{
      vector.fills=[bindColor(paint(cell.check),prefix+".states-"+checked+"-"+arm+"-checkFill")];
      vector.strokes=[];
    }
    vector.resizeWithoutConstraints(geom.check.w,geom.check.h);
    bindFloat(vector,"width",prefix+".check-width");
    bindFloat(vector,"height",prefix+".check-height");
    box.appendChild(vector);
    const label=await paintLabel();
    label.name="checkbox/label :: font-provenance="+encodeURIComponent(JSON.stringify(fontSpec));
    label.fills=[bindColor(paint(cell.label),prefix+".states-"+checked+"-"+arm+"-label")];
    bindFloat(label,"fontSize",prefix+".labelFontSize");
    if(geom.lineHeightUnit==="PIXELS")bindFloat(label,"lineHeight",prefix+".labelLineHeight");
    component.appendChild(label);
    component.layoutSizingHorizontal="HUG";
    component.layoutSizingVertical="HUG";
    if(component.layoutMode!=="HORIZONTAL")throw new Error("CHECKBOX-FAKE-LAYOUT:"+component.name);
    components.push(component);
  }
}
const set=figma.combineAsVariants(components,section);
void "CHECKBOX-WRITER-SET-NAME-CARRIES-COMPILE-LABEL";
void "CHECKBOX-WRITER-VECTOR-PATH";
set.name="checkbox/set :: MUI Checkbox";
set.description="Experimental checkbox@1 primitive-IR mint. Recipe "+recipeHash+"; source adapter "+adapterIdentity+".";
set.layoutMode="VERTICAL";
set.primaryAxisAlignItems="MIN";
set.counterAxisAlignItems="MIN";
set.itemSpacing=16;
set.paddingTop=16;set.paddingRight=16;set.paddingBottom=16;set.paddingLeft=16;
set.fills=[];
set.layoutSizingHorizontal="HUG";
set.layoutSizingVertical="HUG";
set.setSharedPluginData(NS,"runIdentity",runIdentity);
set.setSharedPluginData(NS,"adapterIdentity",adapterIdentity);
set.setSharedPluginData(NS,"recipeHash",recipeHash);
set.setSharedPluginData(NS,"envelopeHash",envelopeHash);
const arrange=figma.createFrame();
arrange.name="Arrange / Checkbox / MUI / "+runIdentity;
arrange.layoutMode="VERTICAL";
arrange.primaryAxisAlignItems="MIN";
arrange.counterAxisAlignItems="MIN";
arrange.itemSpacing=0;
arrange.paddingTop=40;arrange.paddingRight=40;arrange.paddingBottom=40;arrange.paddingLeft=40;
arrange.fills=[{type:"SOLID",color:{r:1,g:1,b:1}}];
arrange.topLeftRadius=8;arrange.topRightRadius=8;arrange.bottomRightRadius=8;arrange.bottomLeftRadius=8;
section.appendChild(arrange);
arrange.appendChild(set);
arrange.layoutSizingHorizontal="HUG";
arrange.layoutSizingVertical="HUG";
arrange.x=40;arrange.y=40;
const review=figma.createFrame();
review.name="Review / Checkbox / MUI / "+runIdentity;
review.layoutMode="VERTICAL";
review.primaryAxisAlignItems="MIN";
review.counterAxisAlignItems="MIN";
review.itemSpacing=16;
review.paddingTop=24;review.paddingRight=24;review.paddingBottom=24;review.paddingLeft=24;
review.fills=[{type:"SOLID",color:{r:1,g:1,b:1}}];
review.topLeftRadius=8;review.topRightRadius=8;review.bottomRightRadius=8;review.bottomLeftRadius=8;
section.appendChild(review);
for(const variant of set.children){
  const instance=variant.createInstance();
  instance.name=variant.name;
  review.appendChild(instance);
}
if(review.children.length!==set.children.length)throw new Error("CHECKBOX-REVIEW-VARIANT-MISMATCH:"+review.children.length);
review.layoutSizingHorizontal="HUG";
review.layoutSizingVertical="HUG";
review.x=arrange.x+arrange.width+40;
review.y=arrange.y;
if(page.children.some(n=>n.name==="Component Container"))throw new Error("CHECKBOX-PAGE-LEVEL-COMPONENT-CONTAINER");
section.resizeWithoutConstraints(Math.max(arrange.x+arrange.width,review.x+review.width)+80,Math.max(arrange.y+arrange.height,review.y+review.height)+80);
return{pageId:page.id,pageName:page.name,sectionId:section.id,setId:set.id,arrangeId:arrange.id,reviewId:review.id,collectionId:collection.id,variantCount:set.children.length,reviewCount:review.children.length,adapterIdentity,recipeHash,paintedFont};
