if(figma.fileKey!=="byMp6lt0Ij9b2QbkDGFwBh")throw new Error("WRONG-FILE:"+figma.fileKey);
if(figma.root.name!=="Scratch Project")throw new Error("WRONG-FILE-NAME:"+figma.root.name);
const NS="ds.contracts.checkbox.recipe.v1";
const runIdentity="548cf953-c8ce9a83-7856869a-checkbox-v2";
const pageName="Recipe Pivot / Checkbox / 548cf953-c8ce9a83-7856869a-checkbox-v2";
const adapterIdentity="astryx-checkbox-reviewed-v1";
const recipeHash="548cf95362cf7ea99fd42cf4b4d21c6a7fe01495bce805029cf3a85a1267f51b";
const envelopeHash="6691e51fa506878b43f6928ba31f430d1071a69126e998f40cdd54f3150c42f4";
const signed=["115:295378","163:35981","183:70641","183:69150","85:6781","173:48924","181:64873","183:74742"];
await figma.loadAllPagesAsync();
const page=figma.root.children.find(p=>p.name===pageName);
if(!page)throw new Error("CHECKBOX-PAGE-MISSING");
if(signed.includes(page.id))throw new Error("CHECKBOX-MUST-NOT-WRITE-SIGNED-PAGE:"+page.id);
if(page.getSharedPluginData(NS,"runIdentity")!==runIdentity)throw new Error("CHECKBOX-PAGE-IDENTITY-MISMATCH:"+page.id);
await figma.setCurrentPageAsync(page);
if(page.children.some(n=>n.type==="SECTION"&&n.getSharedPluginData(NS,"adapterIdentity")===adapterIdentity))throw new Error("CHECKBOX-SECTION-EXISTS:"+adapterIdentity);
const hex=v=>({r:parseInt(v.slice(1,3),16)/255,g:parseInt(v.slice(3,5),16)/255,b:parseInt(v.slice(5,7),16)/255,a:parseInt(v.slice(7,9),16)/255});
const paint=v=>{const c=hex(v);return{type:"SOLID",color:{r:c.r,g:c.g,b:c.b},opacity:c.a};};
const allFonts=await figma.listAvailableFontsAsync();
const fontSpec={"requestedFamily":"-apple-system","requestedStyle":"Medium","resolvedFamily":"SF Pro","resolvedStyle":"Medium","resolution":"fallback","fallbackChain":[{"family":"-apple-system","style":"Medium"},{"family":"SF Pro","style":"Medium"},{"family":"Segoe UI","style":"Semibold"},{"family":"Roboto","style":"Medium"},{"family":"Helvetica","style":"Bold"},{"family":"Arial","style":"Bold"}],"degradation":"source -apple-system stack; Figma cannot load a CSS stack; first named host font is SF Pro Medium"};
const found=fontSpec.fallbackChain.map(c=>allFonts.find(f=>f.fontName.family===c.family&&f.fontName.style===c.style)).find(Boolean);
if(!found)throw new Error("CHECKBOX-FONT-UNAVAILABLE:"+fontSpec.requestedFamily);
if(found.fontName.family!==fontSpec.resolvedFamily||found.fontName.style!==fontSpec.resolvedStyle)throw new Error("CHECKBOX-FONT-PROVENANCE-TAMPER:"+found.fontName.family);
await figma.loadFontAsync(found.fontName);
const collectionName="Recipe Checkbox / "+runIdentity+" / "+adapterIdentity;
const locals=figma.variables.getLocalVariableCollectionsAsync?await figma.variables.getLocalVariableCollectionsAsync():[];
if(locals.some(c=>c.name===collectionName))throw new Error("CHECKBOX-VARIABLE-COLLECTION-COLLISION:"+collectionName);
const collection=figma.variables.createVariableCollection(collectionName);
collection.renameMode(collection.modes[0].modeId,"Default");
collection.hiddenFromPublishing=true;
const modeId=collection.modes[0].modeId;
const prefix="astryx.checkbox";
const planned=[["FLOAT","astryx.checkbox.wrapper-size",24],["FLOAT","astryx.checkbox.box-size",22],["FLOAT","astryx.checkbox.box-radius",4],["FLOAT","astryx.checkbox.box-borderWidth",1],["FLOAT","astryx.checkbox.box-padding",0],["FLOAT","astryx.checkbox.row-gap",8],["FLOAT","astryx.checkbox.dash-width",12],["FLOAT","astryx.checkbox.dash-height",2],["FLOAT","astryx.checkbox.dash-radius",1],["FLOAT","astryx.checkbox.check-width",14],["FLOAT","astryx.checkbox.check-height",14],["FLOAT","astryx.checkbox.check-strokeWidth",2.1],["FLOAT","astryx.checkbox.labelFontSize",14],["COLOR","astryx.checkbox.states-unchecked-enabled-boxFill","#ffffffff"],["COLOR","astryx.checkbox.states-unchecked-enabled-boxBorder","#ccd3dbff"],["COLOR","astryx.checkbox.states-unchecked-enabled-label","#4e606fff"],["COLOR","astryx.checkbox.states-unchecked-enabled-dashFill","#00000000"],["COLOR","astryx.checkbox.states-unchecked-enabled-checkFill","#ffffffff"],["COLOR","astryx.checkbox.states-unchecked-disabled-boxFill","#0536590c"],["COLOR","astryx.checkbox.states-unchecked-disabled-boxBorder","#05365919"],["COLOR","astryx.checkbox.states-unchecked-disabled-label","#a4b0bcff"],["COLOR","astryx.checkbox.states-unchecked-disabled-dashFill","#00000000"],["COLOR","astryx.checkbox.states-unchecked-disabled-checkFill","#ffffffff"],["COLOR","astryx.checkbox.states-checked-enabled-boxFill","#0064e0ff"],["COLOR","astryx.checkbox.states-checked-enabled-boxBorder","#0064e0ff"],["COLOR","astryx.checkbox.states-checked-enabled-label","#4e606fff"],["COLOR","astryx.checkbox.states-checked-enabled-dashFill","#00000000"],["COLOR","astryx.checkbox.states-checked-enabled-checkFill","#ffffffff"],["COLOR","astryx.checkbox.states-checked-disabled-boxFill","#0064e0ff"],["COLOR","astryx.checkbox.states-checked-disabled-boxBorder","#05365919"],["COLOR","astryx.checkbox.states-checked-disabled-label","#a4b0bcff"],["COLOR","astryx.checkbox.states-checked-disabled-dashFill","#00000000"],["COLOR","astryx.checkbox.states-checked-disabled-checkFill","#ffffffff"],["COLOR","astryx.checkbox.states-indeterminate-enabled-boxFill","#0064e0ff"],["COLOR","astryx.checkbox.states-indeterminate-enabled-boxBorder","#0064e0ff"],["COLOR","astryx.checkbox.states-indeterminate-enabled-label","#4e606fff"],["COLOR","astryx.checkbox.states-indeterminate-enabled-dashFill","#ffffffff"],["COLOR","astryx.checkbox.states-indeterminate-enabled-checkFill","#ffffffff"],["COLOR","astryx.checkbox.states-indeterminate-disabled-boxFill","#0064e0ff"],["COLOR","astryx.checkbox.states-indeterminate-disabled-boxBorder","#05365919"],["COLOR","astryx.checkbox.states-indeterminate-disabled-label","#a4b0bcff"],["COLOR","astryx.checkbox.states-indeterminate-disabled-dashFill","#ffffffff"],["COLOR","astryx.checkbox.states-indeterminate-disabled-checkFill","#ffffffff"]];
const vars=new Map();
for(const [type,identity,value] of planned){
  const name="token/"+(type==="COLOR"?"color":"float")+"/id-"+Array.from(identity).map(ch=>ch.charCodeAt(0).toString(16).padStart(2,"0")).join("");
  const variable=figma.variables.createVariable(name,collection,type);
  variable.scopes=["ALL_SCOPES"];
  variable.setValueForMode(modeId,type==="COLOR"?hex(value):value);
  vars.set(type+":"+identity,variable);
}
const bindColor=(base,identity)=>figma.variables.setBoundVariableForPaint(base,"color",vars.get("COLOR:"+identity));
const bindFloat=(node,field,identity)=>node.setBoundVariable(field,vars.get("FLOAT:"+identity));
const geom={"wrapper":24,"box":22,"radius":4,"border":1,"padding":0,"gap":8,"dash":{"w":12,"h":2,"r":1},"check":{"path":"M11.9 3.5 L5.6 10.5 L2.1 7","w":14,"h":14,"stroke":2.1,"paint":"stroke","cap":"ROUND","join":"ROUND","rotation":0,"placement":"center","x":0,"y":0},"fontSize":14,"lineHeightUnit":"AUTO","lineHeight":0,"rowAlign":"CENTER","cells":{"unchecked/false":{"box":"#ffffffff","border":"#ccd3dbff","op":1,"label":"#4e606fff","dash":"#00000000","check":"#ffffffff"},"unchecked/true":{"box":"#0536590c","border":"#05365919","op":0.5,"label":"#a4b0bcff","dash":"#00000000","check":"#ffffffff"},"checked/false":{"box":"#0064e0ff","border":"#0064e0ff","op":1,"label":"#4e606fff","dash":"#00000000","check":"#ffffffff"},"checked/true":{"box":"#0064e0ff","border":"#05365919","op":0.5,"label":"#a4b0bcff","dash":"#00000000","check":"#ffffffff"},"indeterminate/false":{"box":"#0064e0ff","border":"#0064e0ff","op":1,"label":"#4e606fff","dash":"#ffffffff","check":"#ffffffff"},"indeterminate/true":{"box":"#0064e0ff","border":"#05365919","op":0.5,"label":"#a4b0bcff","dash":"#ffffffff","check":"#ffffffff"}}};
let paintedFont=found.fontName;
const paintLabel=async()=>{
  const label=figma.createText();
  label.fontName=paintedFont;
  label.characters="Accept terms";
  label.fontSize=geom.fontSize;
  label.lineHeight=geom.lineHeightUnit==="PIXELS"?{unit:"PIXELS",value:geom.lineHeight}:{unit:"AUTO"};
  label.textAlignHorizontal="LEFT";
  label.textAlignVertical="CENTER";
  label.textAutoResize="WIDTH_AND_HEIGHT";
  if(label.characters.trim().length>0&&(label.width<=0||label.absoluteRenderBounds===null)){
    let ok=false;
    for(const candidate of fontSpec.fallbackChain){
      if(candidate.family===fontSpec.resolvedFamily&&candidate.style===fontSpec.resolvedStyle)continue;
      const next=allFonts.find(e=>e.fontName.family===candidate.family&&e.fontName.style===candidate.style);
      if(!next)continue;
      await figma.loadFontAsync(next.fontName);
      label.fontName=next.fontName;
      label.characters="Accept terms";
      if(label.width>0&&label.absoluteRenderBounds){paintedFont=next.fontName;ok=true;break;}
    }
    if(!ok&&(label.width<=0||label.absoluteRenderBounds===null))throw new Error("CHECKBOX-FONT-ZERO-INTRINSIC");
  }
  if(label.width<=0||label.height<=0)throw new Error("CHECKBOX-TEXT-GEOMETRY");
  return label;
};
let nextX=0;
for(const child of page.children){if(child.type==="SECTION")nextX=Math.max(nextX,child.x+child.width+240);}
const section=figma.createSection();
section.name="Recipe Pivot / Astryx / "+recipeHash.slice(0,8);
section.x=nextX;section.y=0;page.appendChild(section);
section.setSharedPluginData(NS,"adapterIdentity",adapterIdentity);
section.setSharedPluginData(NS,"recipeHash",recipeHash);
section.setSharedPluginData(NS,"variableCollectionId",collection.id);
const components=[];
for(const checked of ["unchecked","checked","indeterminate"]){
  for(const disabled of ["false","true"]){
    const arm=disabled==="true"?"disabled":"enabled";
    const cell=geom.cells[checked+"/"+disabled];
    const component=figma.createComponent();
    component.clipsContent=false;
    component.name="Checked="+checked+", Disabled="+disabled;
    component.layoutMode="HORIZONTAL";
    component.primaryAxisAlignItems="MIN";
    component.counterAxisAlignItems=geom.rowAlign;
    component.itemSpacing=geom.gap;
    component.fills=[];
    bindFloat(component,"itemSpacing",prefix+".row-gap");
    section.appendChild(component);
    const hit=figma.createFrame();
    hit.name="checkbox/hit";
    hit.layoutMode="HORIZONTAL";
    hit.primaryAxisAlignItems="CENTER";
    hit.counterAxisAlignItems="CENTER";
    hit.itemSpacing=0;
    hit.fills=[];
    hit.clipsContent=false;
    hit.paddingTop=geom.padding;hit.paddingRight=geom.padding;hit.paddingBottom=geom.padding;hit.paddingLeft=geom.padding;
    hit.resizeWithoutConstraints(geom.wrapper,geom.wrapper);
    hit.layoutSizingHorizontal="FIXED";hit.layoutSizingVertical="FIXED";
    bindFloat(hit,"width",prefix+".wrapper-size");
    bindFloat(hit,"height",prefix+".wrapper-size");
    component.appendChild(hit);
    const box=figma.createFrame();
    box.name="checkbox/box";
    box.layoutMode="HORIZONTAL";
    box.primaryAxisAlignItems="CENTER";
    box.counterAxisAlignItems="CENTER";
    box.itemSpacing=0;
    box.opacity=cell.op;
    box.clipsContent=geom.check.placement!=="absolute";
    box.resizeWithoutConstraints(geom.box,geom.box);
    box.layoutSizingHorizontal="FIXED";box.layoutSizingVertical="FIXED";
    box.fills=[bindColor(paint(cell.box),prefix+".states-"+checked+"-"+arm+"-boxFill")];
    box.strokes=[bindColor(paint(cell.border),prefix+".states-"+checked+"-"+arm+"-boxBorder")];
    box.strokeWeight=geom.border;box.strokeAlign="INSIDE";
    box.topLeftRadius=geom.radius;box.topRightRadius=geom.radius;box.bottomRightRadius=geom.radius;box.bottomLeftRadius=geom.radius;
    bindFloat(box,"width",prefix+".box-size");
    bindFloat(box,"height",prefix+".box-size");
    bindFloat(box,"strokeWeight",prefix+".box-borderWidth");
    bindFloat(box,"topLeftRadius",prefix+".box-radius");
    bindFloat(box,"topRightRadius",prefix+".box-radius");
    bindFloat(box,"bottomRightRadius",prefix+".box-radius");
    bindFloat(box,"bottomLeftRadius",prefix+".box-radius");
    hit.appendChild(box);
    const dash=figma.createFrame();
    dash.name="checkbox/glyph/dash";
    dash.visible=checked==="indeterminate";
    dash.layoutMode="HORIZONTAL";
    dash.resizeWithoutConstraints(geom.dash.w,geom.dash.h);
    dash.layoutSizingHorizontal="FIXED";dash.layoutSizingVertical="FIXED";
    dash.fills=[bindColor(paint(cell.dash),prefix+".states-"+checked+"-"+arm+"-dashFill")];
    dash.topLeftRadius=geom.dash.r;dash.topRightRadius=geom.dash.r;dash.bottomRightRadius=geom.dash.r;dash.bottomLeftRadius=geom.dash.r;
    bindFloat(dash,"width",prefix+".dash-width");
    bindFloat(dash,"height",prefix+".dash-height");
    box.appendChild(dash);
    const vector=figma.createVector();
    vector.name="checkbox/glyph/check";
    vector.visible=checked==="checked";
    vector.vectorPaths=[{windingRule:"NONZERO",data:geom.check.path}];
    vector.strokeCap=geom.check.cap;
    vector.strokeJoin=geom.check.join;
    if(geom.check.rotation)vector.rotation=geom.check.rotation;
    if(geom.check.paint==="stroke"){
      vector.fills=[];
      vector.strokes=[bindColor(paint(cell.check),prefix+".states-"+checked+"-"+arm+"-checkFill")];
      vector.strokeWeight=geom.check.stroke;
      vector.strokeAlign="CENTER";
      bindFloat(vector,"strokeWeight",prefix+".check-strokeWidth");
    }else{
      vector.fills=[bindColor(paint(cell.check),prefix+".states-"+checked+"-"+arm+"-checkFill")];
      vector.strokes=[];
    }
    vector.resizeWithoutConstraints(geom.check.w,geom.check.h);
    bindFloat(vector,"width",prefix+".check-width");
    bindFloat(vector,"height",prefix+".check-height");
    if(geom.check.placement==="absolute"){
      const host=figma.createFrame();
      host.name="checkbox/glyph/check-host";
      host.layoutMode="HORIZONTAL";
      host.primaryAxisAlignItems="CENTER";
      host.counterAxisAlignItems="CENTER";
      host.fills=[];
      host.clipsContent=false;
      host.appendChild(vector);
      box.appendChild(host);
      host.layoutPositioning="ABSOLUTE";
      host.x=geom.check.x;host.y=geom.check.y;
      host.constraints={horizontal:"MIN",vertical:"MIN"};
      host.resizeWithoutConstraints(geom.check.w,geom.check.h);
      host.layoutSizingHorizontal="FIXED";host.layoutSizingVertical="FIXED";
    }else box.appendChild(vector);
    const label=await paintLabel();
    label.name="checkbox/label :: font-provenance="+encodeURIComponent(JSON.stringify(fontSpec));
    label.fills=[bindColor(paint(cell.label),prefix+".states-"+checked+"-"+arm+"-label")];
    bindFloat(label,"fontSize",prefix+".labelFontSize");
    if(geom.lineHeightUnit==="PIXELS")bindFloat(label,"lineHeight",prefix+".labelLineHeight");
    component.appendChild(label);
    component.layoutSizingHorizontal="HUG";
    component.layoutSizingVertical="HUG";
    if(component.layoutMode!=="HORIZONTAL")throw new Error("CHECKBOX-FAKE-LAYOUT:"+component.name);
    components.push(component);
  }
}
const set=figma.combineAsVariants(components,section);
void "CHECKBOX-WRITER-SET-NAME-CARRIES-COMPILE-LABEL";
void "CHECKBOX-WRITER-VECTOR-PATH";
set.name="checkbox/set :: Astryx CheckboxInput";
set.description="Experimental checkbox@1 primitive-IR mint. Recipe "+recipeHash+"; source adapter "+adapterIdentity+".";
set.layoutMode="VERTICAL";
set.primaryAxisAlignItems="MIN";
set.counterAxisAlignItems="MIN";
set.itemSpacing=16;
set.paddingTop=16;set.paddingRight=16;set.paddingBottom=16;set.paddingLeft=16;
set.fills=[];
set.layoutSizingHorizontal="HUG";
set.layoutSizingVertical="HUG";
set.setSharedPluginData(NS,"runIdentity",runIdentity);
set.setSharedPluginData(NS,"adapterIdentity",adapterIdentity);
set.setSharedPluginData(NS,"recipeHash",recipeHash);
set.setSharedPluginData(NS,"envelopeHash",envelopeHash);
set.x=80;set.y=96;
section.resizeWithoutConstraints(set.width+160,set.y+set.height+80);
return{pageId:page.id,pageName:page.name,sectionId:section.id,setId:set.id,collectionId:collection.id,variantCount:set.children.length,adapterIdentity,recipeHash,paintedFont};
